### ISSUE TITLE
Implement RuboCop across socketry

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#10]
This is not something I'd personally want to do, but I'm not against it completely either.

Let's have a discussion here and see where it ends up.

**Comment by ioquatix** [comment]
@nickcannariato I invite you to follow this issue w.r.t. whitespace handling on github.

**Comment by picatz** [comment]
2-spaces 4-life.

**Comment by tarcieri** [comment]
2 spaces definitely seems like the Ruby convention:

https://ukupat.github.io/tabs-or-spaces/

![screen shot 2017-04-09 at 6 46 01 pm](https://cloud.githubusercontent.com/assets/797/24843152/d9837398-1d54-11e7-9ef6-70ebe42692af.png)

**Comment by ioquatix** [comment]
I love that page, it's awesome that someone took the time to make it. Trust me, I'm well aware that most Ruby code uses 2 spaces. Except of course, MRI interpreter itself which is a cluster fuck of tabs and spaces, and let's not forget the standard library, which is also a pretty huge mess. Honestly, even thought the issue was brought up several times with Matz, he just doesn't seem to give a fuck.

Frankly, PHP used to be the convention for web apps. What's convention today isn't convention tomorrow. "convention" isn't a good yard stick by which to measure anything IMHO. Honestly, there is a ton of crap which is justified by being a "convention".

The conviction I have for using tabs is based on writing code for over 15 years. I write code in C, C++, Java, JavaScript, and tons of other languages, and I have an internal convention for indentation which is consistent across all my projects.

What WILL contribute to this discussion is actual practical technical reasons - things like "I can't configure my editor to use tabs T#!%G!#RG" or "GitHub is a flaming pile of bollocks and can't format code correctly". Those are valid reasons for using spaces for indentation, but they need to be weight up against things like "I prefer to have 2 space indentation on my laptop and 4 space indentation on my desktop, and I'm the one doing all the work right now, so I'm going to optimise for my needs".

**Comment by ioquatix** [comment]
Oh, and the other argument, as discussed here, is that people won't contribute to a project if it's using tabs: https://github.com/ioquatix/rack-freeze/issues/2

Yet, we changed to spaces, and all it did, is made me, the maintainer, less enthusiastic about working on it more (yes, I have a idea for a feature I'd like to add, and yes, I am now in a position where I don't really want to work on that code base, it's less appealing than other projects).

**Comment by ioquatix** [comment]
For reference, here is the issue about github not respecting `.editorconfig` which at the very least would help solve some of these issues: 

https://github.com/github/markup/issues/1045#issuecomment-292831494

**Comment by tarcieri** [comment]
> The conviction I have for using tabs is based on writing code for over 15 years. I write code in C, C++, Java, JavaScript, and tons of other languages, and I have an internal convention for indentation which is consistent across all my projects.

For comparison, I'm implementing something in 5 languages right now. I'm using a mixture of 2-spaces (Ruby, TypeScript), 4-spaces (Python, Rust), and tabs (Go). Using a consistent indentation style between projects means less to me than using an indentation style consistent to what's common in the language, and what are the defaults for the linting tools (I'm using e.g. gofmt, rustfmt, tsfmt, and RuboCop)

The problem with using an uncommon indentation style, especially in a language where there's almost universal agreement on what indentation style should be used, is that it makes your code look weird and alien to people who are used to seeing everything with a consistent indentation style.

That, and the linter is going to tell you your style is wrong.

**Comment by ioquatix** [comment]
I am going to lock this conversation, I still want contributions, but only from actual members or contributors. My experience in the past is that people see the bandwagon and jump on. So far the conversation has been good, and I want to keep it at that level.

**Comment by ioquatix** [comment]
> For comparison, I'm implementing something in 5 languages right now. I'm using a mixture of 2-spaces (Ruby, TypeScript), 4-spaces (Python, Rust), and tabs (Go). Using a consistent indentation style between projects means less to me than using an indentation style consistent to what's common in the language, and what are the defaults for the linting tools (I'm using e.g. gofmt, rustfmt, tsfmt, and RuboCop)

@tarcieri I really like what you've said here.

It makes a lot of sense.

I think it helped me understand more of the issue.

One can either choose to be internally consistent (across your own projects) w.r.t. style, or externally consistent (across specific languages).

For me, up to this point, I've always placed more value on being internally consistent, because what I've seen over years, and languages, is that trying to be externally consistent is a moving target. But, what you've said really helps clarify the situation a lot so thanks.

**Comment by picatz** [comment]
My first thought when I wanted to contribute to stuff was "gotta change dem tabz"; and in general, in order to be more widely appealing, even at the contributor level, I figured it'd be something to think about. 

And I'm glad we're doing that! 💃 

I don't really think the 2-spaces argument is about more contributions, less bugs, making things easier to maintain completely; and I especially don't stand behind the argument that it's just what I personally prefer as being an acceptable reason.

## Mah Reasonz
If we're speaking a language, and we want it to be best understood by those who speak that language, then it may be best ( in some situations ) to adopt the standards of that language in order to communicate the ideas in that language in the best possible way.

### More Important
Now, I guess when it comes down to it, if it were to honestly make @ioquatix less excited to work on this stuff -- t**hen I want no part in this campaign for 2-space justice any longer**. Sure, I'd disagree with it a little. But, for real, if you really don't want the 2-spaces then I won't harass you about it anymore and I'll work around it.

#### Ruby
Becuase if it made you less happy, then it probably wouldn't be all that ruby like. Sure, it'd make me happy -- but I didn't really do anything.

With that said: `#2-spaces4-life-squad-comen-8u-4real-2good-1life-0choices-whatamidoing`

**Comment by ioquatix** [comment]
I've been working on several gems using spaces for experience. I decided not to change them and just try using spaces for indentation.

I found using spaces for indentation pretty meh. In the gems I took on maintaining, I found a few issues:

- Markdown requires for spaces indented code blocks, but only a single tab. Using spaces for indented code blocks is a bit counter-intuitive if you are expecting to use 2-space indents for everything else. Code fences are more consistent, but a bit ugly for single line examples.
- Editors generally work fine for either configuration, tabs or spaces.
- Alignment of things, e.g. the way bundler by default aligns `=` in `.gemspec` files is generally broken by design across most of the gems I've looked at. I think it would just be better to avoid doing this.
- Code that predominantly uses spaces for indentation (e.g. 2-space), especially old code, subjectively seems more likely to have odd issues, like 3-space indentation mixed with 2-space, the occasional tab, etc.
- Mixing code that uses 4-spaces for indentation and 2-spaces for indentation almost always causes problems - I normally have to end up reformatting it all by hand. This applies to basically any code which uses different width for indentation. The algorithm to convert tabs-to-spaces and spaces-to-tabs almost always does the wrong thing if you have Atom set up to use 4-character wide spaces. The counter point is that mixing code that uses tabs never has any issue since tab width is a display preference not affecting the actual code itself.

Additionally, my experiment with `rack-freeze` (converting from tabs to spaces) didn't generate useful contributions. Yet, my code in `http-accept` which uses tabs had a set of really awesome PRs supplied.

**Comment by ioquatix** [comment]
Now that I maintain both kinds of indentation, honestly, I care even less about it, but day-to-day my preference is still to use tabs as it basically just seems semantically better and I can change the tab width depending on my display resolution. I can't see any way to do that with spaces for indentation.
