### ISSUE TITLE
Scheduler Wrapper objects aren't reused

### ISSUE THREAD

**Issue by bruno-** [socketry/async#100]
I continued playing with PR #97 and I think I discovered another bug in `master` (not related to weakmap from #97).
Here's what happens:

- `Scheduler#from_io` always receives a different `io` object.
- It seems `@wrappers` hash never reuses `Wrapper` objects. It currently just leaks memory.

Here's the spec that reproduces this with `puts` debug statements and comments:

https://github.com/bruno-/async/pull/1

**Comment by bruno-** [comment]
I investigated ruby's Scheduler PR.

I found two places where ruby is creating a new IO object (from a file descriptor) when it invokes `rb_scheduler_io_wait`

1. https://github.com/ruby/ruby/blob/71c746379d5872e250d90ae45c585760afaf9516/io.c#L1384

2. https://github.com/ruby/ruby/blob/71c746379d5872e250d90ae45c585760afaf9516/io.c#L11024

There is one place where `rb_scheduler_io_wait` is called and it reuses an existing IO:

https://github.com/ruby/ruby/blob/71c746379d5872e250d90ae45c585760afaf9516/io.c#L1270

I guess the first two links confirm ruby is in some cases creating a new "throwaway" IO object for every call to `Scheduler#io_wait`.

**Comment by ioquatix** [comment]
Yes, I wrote that code haha.

It's ugly but we cannot do anything about it since it's a public C interface which accepts a file descriptor.

A solution is to cache the objects internally but that causes more issues as you've observed.

So in this case, we should ensure all interfaces we have control over are using the code path which provides an IO instance.

**Comment by bruno-** [comment]
> So in this case, we should ensure all interfaces we have control over are using the code path which provides an IO instance.

Ok, so just to clarify: this is something that should be addressed in ruby source? If yea, that makes sense.

Do you think it would be worth it to disable `@wrappers` caching in `Async::Scheduler` until this is fixed? I think that currently just leaks memory and file descriptors as there's no reuse, right?

**Comment by ioquatix** [comment]
I decided to remove the wrapper cache for now.
