### ISSUE TITLE
Net::HTTP fails inside Async block

### ISSUE THREAD

**Issue by orlando-labs** [socketry/async#102]
Hi, @ioquatix.
There's a call
```ruby
@socket.io.to_io.wait_readable(0)
```
in ruby-3.0.0/lib/ruby/3.0.0/net/http.rb:1602

So when it's wrapped into Async block (inside falcon, for example), then it will fail with Async::TimeoutError instead of acting like it's supposed to: "Waits until input is available or times out and returns self or nil when EOF is reached."

Simple reproduction:
```
[usor@srvr awesome_app]$ bundle exec irb
3.0.0 :001 > require 'async'
 => true 
3.0.0 :002 > s1, s2 = Socket.pair :UNIX, :STREAM, 0
 => [#<Socket:fd 5>, #<Socket:fd 7>] 
3.0.0 :003 > Async { s1.wait_readable 0 }
  0.0s    error: Async::Task [oid=0xb2c] [pid=460088] [2021-02-16 11:48:16 +0000]
               |   Async::TimeoutError: execution expired
               ...
3.0.0 :004 > s1.wait_readable 0
 => nil 
```

**Comment by ioquatix** [comment]
Is `wait_readable(0)` supposed to be the same as `wait_readable` with no arguments (i.e. no timeout)?

**Comment by ioquatix** [comment]
I see how this could be a problem, it should return nil - we can fix this.

**Comment by orlando-labs** [comment]
> Is `wait_readable(0)` supposed to be the same as `wait_readable` with no arguments (i.e. no timeout)?

Yes, according to [IO#wait_readable doc](https://docs.ruby-lang.org/en/3.0.0/IO.html#method-i-wait_readable)
