### ISSUE TITLE
Operation: Documentation

### ISSUE THREAD

**Issue by picatz** [socketry/async#12]
So, with the [branch](https://github.com/socketry/async/tree/yarddoc-ahoy) I just made, I'm attempting to add some inline documentation following the [YARD](http://yardoc.org/) style -- because I think that it's awesome like a possum.

![this is an awesome possum](https://cloud.githubusercontent.com/assets/14850816/25051592/7b9f6942-211b-11e7-913f-e3a8322d254a.gif)

### Some Lil Bumps In Da Road
I don't know, like, everything that is going on under the hood for this gem obviously. In general, this is some of my first exposure to IO related concepts. Plus, I get terribly distracted with other things I end up working on ( like a lot of us, I'm sure ). 

So, wherever I obviously am falling short on explanations, I'd appreciate you cool cats ( or dogs ) in helping contribute to the documentation effort.

#### plz
So, please be sure to go over ma' mistakes and help correct them.

## Why YardDoc Ahoy?
Because pirates, of course.

**Comment by ioquatix** [comment]
Sure :)

**Comment by ioquatix** [comment]
I am okay with YARD, I've used it on some projects before. I'm fine with whatever works for now.

**Comment by ioquatix** [comment]
Okay, I've squash merged everything from that branch. I've made quite a few improvements too. Thanks for working on this!

**Comment by ioquatix** [comment]
I'm going to close this issue, as we've merged and improved on everything. However, still looking forward to other improvements :)
