### ISSUE TITLE
Docs no longer working - Github Pages 404

### ISSUE THREAD

**Issue by dishcandanty** [socketry/async#134]
Not seeing any other issues on this, so figured I'd create one. Currently the docs link in the readme is 404ing. Last broken commit?

https://socketry.github.io/async/

![image](https://user-images.githubusercontent.com/2327777/145623385-4bff11ce-4858-4faa-b001-5549fa11a356.png)

**Comment by ioquatix** [comment]
Oops I'll sort it out, thanks!

**Comment by ioquatix** [comment]
This is now fixed, thanks for your report.
