### ISSUE TITLE
latest async 2.0 not compatible with Ruby 2.7.0 

### ISSUE THREAD

**Issue by sivagollapalli** [socketry/async#136]
```
Error installing async:
	There are no versions of io-event (~> 1.0.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	io-event requires Ruby version >= 3.0. The current ruby version is 2.7.0.0.
```

**Comment by ioquatix** [comment]
Yes, you will need to use Async 1.x for Ruby 2.7. Maybe we need to add a version dependency for Async 2.0 otherwise Rubygems cannot cope with it.

**Comment by sivagollapalli** [comment]
So, is there any plan to support 2.7 or we have to switch to Ruby 3 to use async 2.0 ?

**Comment by ioquatix** [comment]
Async 1.0 and Async 2.0 are the same interface, but one is for Ruby without the fiber scheduler and one is for Ruby with the fiber scheduler.e

**Comment by ioquatix** [comment]
If you require any further help, let me know. Async 1.x for Ruby 2.7 and 3.0, Async 2.x for Ruby 3.1+, and Ruby 3.2 will be the first platform which I can be confident in production, since there are a couple of autoload bugs in 3.1.
