### ISSUE TITLE
Async 2.0 issue

### ISSUE THREAD

**Issue by mscrivo** [socketry/async#138]
Sorry for the extremely vague title, but I'm not even sure what the issue is yet, so I couldn't come up with a better one. 

We have some code that uses a number of async tasks to fetch items from S3 in parallel, that roughly looks like this:

```ruby
barrier = Async::Barrier.new
semaphore = Async::Semaphore.new(15)

parent_task =
  Async() do
    models.each do |model|
      semaphore.async(parent: barrier) do
        fetch_from_s3(model)
      end
    end

    barrier.wait
  end

fail parent_task.result if parent_task.failed?
```

This has been working great with async < 2. As soon as I tried upgrading to 2.0, we saw this in our S3 metrics:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/275524/149171118-42a72116-0380-49b2-90b1-5cc201db2148.png">

The number of requests it started making to s3 jumped through the roof, and the vast majority of them errored with: `Errno::EPERM: Operation not permitted - IO_Event_Selector_EPoll_io_wait:epoll_ctl`

As soon as we flipped back to 1.30.1, the issue went away.

**Comment by travisbell** [comment]
Hey @mscrivo odd timing! I recently layered in some Async calls around my S3 usage and am also randomly getting these `Errno::EPERM` errors. I haven't been able to understand them. Unlike you however, I didn't start with `1.x` and have only started with the `2.0` version.

**Comment by ioquatix** [comment]
Oh no, that's not a good picture!

A lot of the code path is new so there will be some pain points like this, thanks for bringing it to my attention.

```
       EPERM  The target file fd does not support epoll.  This error can
              occur if fd refers to, for example, a regular file or a
              directory.
```

This looks like a case where we are being overly optimistic around whether Linux can handle file IO using `epoll`. This shouldn't normally be an issue but let me try to reproduce the issue locally.

**Comment by travisbell** [comment]
Your instincts look good:

```
Errno::EPERM: Operation not permitted - IO_Event_Selector_EPoll_io_wait:epoll_ctl
/usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
/usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
/usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `write'
/usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `puts'
/usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `call'
/usr/local/bundle/gems/console-1.14.0/lib/console/filter.rb:144:in `call'
/usr/local/bundle/gems/console-1.14.0/lib/console/filter.rb:43:in `block (3 levels) in []'
/usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:240:in `fail!'
/usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:264:in `rescue in block in schedule'
/usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:261:in `block in schedule'
```

**Comment by ioquatix** [comment]
Can you tell me are you redirecting stderr to a file?

**Comment by travisbell** [comment]
Yes, I am.

**Comment by ioquatix** [comment]
Okay I should be able to reproduce this.

**Comment by travisbell** [comment]
Hey Sam, in another project that I am working on switching to Falcon, a gem I am using is doing something (I have yet to investigate the specifics) with a tempfile, and am getting the same error, but via a different caller:

```ruby
Errno::EPERM - Operation not permitted - IO_Event_Selector_EPoll_io_wait:epoll_ctl:
	/usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
	/usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
	/usr/local/lib/ruby/3.1.0/delegate.rb:349:in `flush'
	/usr/local/lib/ruby/3.1.0/delegate.rb:349:in `block in delegating_block'
```

So unlike the example above that was from `console`, this one is not. Thought it might help.

**Comment by ioquatix** [comment]
Thanks, yes that's interesting.

I'm not sure how `Tempfile` is implemented but it should be reproducible, so I'll investigate this case too. Maybe there is some internal incompatibility with `tmpfs`?

**Comment by ioquatix** [comment]
Is your file on a `tmpfs` or a regular fs? Do you mind telling me what kind of file system it's on?

**Comment by ioquatix** [comment]
Also, it's odd that it's calling `io_wait` on a file, it means in CRuby, `flush` must have blocked some how.

**Comment by ioquatix** [comment]
@travisbell are you running this in a container and redirecting to some kind of pipe, or is it definitely a local file?

**Comment by travisbell** [comment]
Hey @ioquatix, ok, after some playing I have a pretty simple way I can reproduce it. First off, here's some observations:

1. The error changes to `Resource temporarily unavailable (Errno::EAGAIN)` on Ruby 3.1.1.
2. I cannot reproduce this on Mac OS, only my test Ubuntu container. We deploy on Ubuntu, so this was only showing up in production, not on local dev.
3. The problem only manifests itself when executing within an `Async` block. Outside of one, and I never see an issue. These loops execute fine.
4. The problem is easy to trigger when using the gem I originally discovered it with, `Diffy`.
5. It does not appear whether or not I am logging to a file matters.

Here's my test code, and again, I could not reproduce this on Mac OS, only my test Ubuntu 20.04 container.

```ruby
require 'async'
require 'diffy'
require 'logger'

def async_test_with_logfile
  logger = Logger.new('async_test.log')

  Async do
    begin
      100.times do
        Diffy::Diff.new('hi there, how are?', 'hi there, how are you?').to_s(:html)
      end
    rescue => error
      logger.error(error)
    end
  end
end

def async_test_no_logfile
  Async do
    begin
      100.times do
        Diffy::Diff.new('hi there, how are?', 'hi there, how are you?').to_s(:html)
      end
    rescue => error
      Console.logger.error(error)
    end
  end
end

def sync_test_no_logfile
  begin
    100.times do
      Diffy::Diff.new('hi there, how are?', 'hi there, how are you?').to_s(:html)
    end
  rescue => error
    Console.logger.error(error)
  end
end
```

You might get 5 or 6 runs of either of the async tests to go without any issue but then you'll hit one. I can usually get the error at least once every 10 runs.

**Comment by travisbell** [comment]
Related to my first point, I still see `Errno::EPERM` errors on 3.1.1, it's just not in the blocks of code I used above. So there's a subtle difference as to what is going on, and these specific ones seem harder to replicate.

```ruby
Operation not permitted - IO_Event_Selector_EPoll_io_wait:epoll_ctl
                 /usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
                 /usr/local/bundle/gems/async-2.0.0/lib/async/scheduler.rb:170:in `io_wait'
       /usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `write'
       /usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `puts'
       /usr/local/bundle/gems/console-1.14.0/lib/console/serialized/logger.rb:92:in `call'
               /usr/local/bundle/gems/console-1.14.0/lib/console/filter.rb:144:in `call'
               /usr/local/bundle/gems/console-1.14.0/lib/console/filter.rb:43:in `block (3 levels) in []'
                      /usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:240:in `fail!'
                      /usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:264:in `rescue in block in schedule'
                      /usr/local/bundle/gems/async-2.0.0/lib/async/task.rb:261:in `block in schedule'
```

**Comment by mscrivo** [comment]
I am able to reproduce with @travisbell's sample code on our ubuntu 20.04 based containers as well.

**Comment by ioquatix** [comment]
Great thanks for all this I'll take a look.

**Comment by ioquatix** [comment]
Okay, I was able to reproduce it as part of the test suite: https://github.com/socketry/async/runs/5458553188?check_suite_focus=true#step:4:284

**Comment by ioquatix** [comment]
Looks like it might be related to

```ruby
diff = Open3.popen3(diff_bin, *(diff_options + @paths)) { |i, o, e| o.read }
```

**Comment by ioquatix** [comment]
This should be fixed in `io-event` v1.0.5 which I just released. Can you please try it out and let me know?

**Comment by travisbell** [comment]
I bumped and deployed last night and haven't seen any since but it was always a bit sporadic. I'll give you another update tomorrow.

**Comment by travisbell** [comment]
I'm pretty content to say 1.0.5 fixes the issues I was seeing. It's been 36 hours since I've seen the error, everything looks good.

**Comment by ioquatix** [comment]
@travisbell feel free to close this issue when you are satisfied!

**Comment by travisbell** [comment]
@mscrivo Have you had a chance to give the new version a try?

**Comment by mscrivo** [comment]
All looking good from my end as well, thanks @ioquatix and @travisbell!

**Comment by ioquatix** [comment]
Thanks everyone for your continued support and updates.

**Comment by mscrivo** [comment]
Any particular reason the new version requires ruby 3.1.1? instead of 3.1.0?

**Comment by ioquatix** [comment]
Yes, 3.1.0 has bugs.
