### ISSUE TITLE
waiting for all subtasks?

### ISSUE THREAD

**Issue by emiltin** [socketry/async#140]
How can I wait for a task and all it's subtasks? It sems calling wait() doesn't wait for subtasks:

```ruby
Async do |t1|
  t1.async do |t2|
    t2.async do |t3|
      t3.sleep 1
      p :a
    end
  end.wait
  p :b
end

```
=>
:b
:a

**Comment by ioquatix** [comment]
https://github.com/socketry/async/pull/89

However it may be risky as you don't control all sub-tasks.

**Comment by emiltin** [comment]
Thanks. Since my need for this is in an RSpec testing context, the risk is minimal, so I don't mind simply iterating subtasks and waiting fot them in turn.

**Comment by emiltin** [comment]
Task#stop seems to kill all sub tasks?

**Comment by ioquatix** [comment]
Yes that's correct. This is used by `async-rspec` gem if you want an example:

https://github.com/socketry/async-rspec/blob/66f0ac85218d087b7cc4a60736f2bf8d761acc76/lib/async/rspec/reactor.rb#L63
