### ISSUE TITLE
Does async support using `Fiber.new(blocking: false, &block)` directly

### ISSUE THREAD

**Issue by bruno-** [socketry/async#147]
Hi,

In [fiber_scheduler gem](https://github.com/bruno-/fiber_scheduler) I'm using non-blocking fibers directly, like this:

```ruby
Async do |task|
	Fiber.scheduler.unblock(nil, Fiber.current)

	Fiber.new(blocking: false) do
		sleep 1000
	end.transfer
end
```

The goal here is to create a raw fiber that's the equivalent of a "transient task".

But, I'm getting an error `Closing scheduler with blocked operations! (RuntimeError)` raised from the following line:

https://github.com/socketry/async/blob/456df488d801572821eaf5ec2fda10e3b9744a5f/lib/async/scheduler.rb#L55

So, just to confirm: does async support this workflow?

Thanks

**Comment by ioquatix** [comment]
I believe it's incorrect to call `block` or `unblock` directly.

`Async` and `Fiber.schedule` are compatible together.

**Comment by bruno-** [comment]
Thanks!
