### ISSUE TITLE
Support for SSL Sockets/Server

### ISSUE THREAD

**Issue by rfestag** [socketry/async#16]
I tried using tcp_socket.rb as an example, but don't fully undesrtand how to add support for SSL sockets. Namely, it looks like tasks assume there is a fileno method, but OpenSSL::SSL::Server doesn't have that. The base TCPServer does though. 

I've tried various combinations, but can't seem to get a fileno method that actually proxies down to whatever is supposed to have it. Calling fileno on an Async::TCPServer doesn't work, but when I try to proxy fileno from the internal IO, it seems to be trying to call it on the host parameter string.

Any thoughts on how to implement an SSLServer/SSLSocket for async?

**Comment by rfestag** [comment]
I submitted a PR for an idea on how to do this. Open to input:
https://github.com/socketry/async/pull/17

**Comment by ioquatix** [comment]
Can we please move this to https://github.com/socketry/async-io
