### ISSUE TITLE
tasks run synchronously, it might be nice to capture output/result of fiber

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#2]
Right now, tasks are resumed directly, but perhaps it would make sense for a fiber to capture the "return value" as it were. I'm not sure if this is possible or how much work would be required.

However, as part of this, handling "return" within an async block also needs to be checked - does the reactor blow up?

**Comment by ioquatix** [comment]
I've thought about this a bit more. I think adding `Async::Promise` and `Async::Future` might not be a bad idea. But, perhaps in a separate gem?

Finally, it might make sense to add a really light weight synchronisation primitive, `Async::Task#wait`. This would yield the current fiber until the specified task was complete. However, I wouldn't want to support this if it meant overheat in the main reactor loop. Perhaps, again, this could be a monkey patch by a gem, e.g. `async-future`.

**Comment by tarcieri** [comment]
> Additionally, it might make sense to use Async::Task as really light weight synchronisation primitive, Async::Task#wait. This would yield the current fiber until the specified task was complete.

This sounds an awful lot like `await` from a standard async/await API

**Comment by ioquatix** [comment]
Yeah, your right, it's very similar.

**Comment by ioquatix** [comment]
The output of a fiber is now captured, but there is no synchronisation mechanism in place. It would probably be sufficient to make a simple Fiber condition variable, which is essentially a queue of fibers waiting on the result, which get sequentially resumed once the result is available.
