### ISSUE TITLE
Concurrent behaviour with IO operations, performance issues

### ISSUE THREAD

**Issue by tuwukee** [socketry/async#214]
Hi,

Firstly, thanks a lot for the async libraries, they are very handy to use!
I've been doing some local tests with `async` and noticed that it has a poor performance when concurrent fibers perform IO operations (compared with threads). 

I wonder if there are any limitations/known drawbacks in the scheduler design causing IO performance issues.
Or am I using it incorrectly? Please advice.

For the sake of completeness, I compared `async` results with plain Ruby threads and `polyphony`. 
The test set: 5 concurrent threads/fibers 20 times each run `perform` and the method 1000 times opens and writes text into a file.
Ruby 3.2.0, OSX 12.3 (chip M1)

```ruby
require "async"

CONCURRENCY = 5
JOBS_COUNT = 100 / CONCURRENCY

def perform(idx, name)
  1000.times do
    File.open(name, "a") { |f| f.write "#{idx}\n" }
  end
end

puts "CONCURRENCY: #{CONCURRENCY}"
puts "STARTING THREADS..."
start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
threads = []
th_name = "tmp/logs/threads.txt"
CONCURRENCY.times do
  threads << Thread.new do
    JOBS_COUNT.times do |i|
      perform(i, th_name)
    end
  end
end
threads.each(&:join)
puts "FINISHED THREADS... TIME: #{Process.clock_gettime(Process::CLOCK_MONOTONIC) - start}"

puts "STARTING ASYNC FIBERS..."
start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
async_name = "tmp/logs/async.txt"
task = Async do
  CONCURRENCY.times.map do |i|
    Async do
      JOBS_COUNT.times do |j|
        perform(j, async_name)
      end
    end
  end
end
task.wait
puts "FINISHED ASYNC FIBERS... TIME: #{Process.clock_gettime(Process::CLOCK_MONOTONIC) - start}"

# `require "polyphony"` breaks async, so run it in a fork or separately
p = fork do
  require "polyphony"
  puts "STARTING POLY FIBERS..."
  start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  poly_name = "tmp/logs/poly.txt"
  tasks = CONCURRENCY.times.map do |i|
    spin do
      JOBS_COUNT.times do |j|
        perform(j, poly_name)
      end
    end    
  end
  tasks.each(&:await)
  puts "FINISHED POLY FIBERS... TIME: #{Process.clock_gettime(Process::CLOCK_MONOTONIC) - start}"
end
Process.wait(p)
```

Results:

```
CONCURRENCY: 5
STARTING THREADS...
FINISHED THREADS... TIME: 1.1868729996494949
STARTING ASYNC FIBERS...
FINISHED ASYNC FIBERS... TIME: 2.0718310000374913
STARTING POLY FIBERS...
FINISHED POLY FIBERS... TIME: 0.8345299996435642
```
I've run a similar test with `net/http` requests within the `perform` method and `async` also has the worst results among these 3. 
The only IO operation where `async` outperforms threads (but not `polyphony`) that I found out so far is `sleep`.

**Comment by ioquatix** [comment]
File IO is not non-blocking on a M1 Mac (i.e. Darwin) so this is not a particularly good benchmark IIUC.

**Comment by ioquatix** [comment]
`io_uring` is a more general interface for asynchronous OS system calls.

It's a nicer and more general interface to implement the behaviour we want.

There are some cases we can optimise for but at the moment, all the operations are one-shot, which at worst requires one system call per operation, but longer term we should be able to reduce that. One part of that limitation is that we are beholden to the intersection of all event driven interfaces, e.g. epoll, kqueue, io_uring, etc.

Longer term, I'll look at specific ways we can take advantage of it. `io_uring` should show advantages on busy systems, but we don't approach that limit yet (we run into other performance issues first e.g. GC).

**Comment by tuwukee** [comment]
Thanks for the explanation, closing the issue
