### ISSUE TITLE
Requested to open issue from LightIO discussion re: Ruby 2.5

### ISSUE THREAD

**Issue by 98-f355-f1** [socketry/async#22]
I was requested to open an issue for the async io section: forgive me if this is not the correct place.

I am playing around with the gems and the async-http example on the read me page, shows the following errors:
For the async-http, when I run the async-http example.
Traceback (most recent call last):
11: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-1.10.0/lib/async/task.rb:74:in block in initialize' 10: from ./async-http.rb:20:inblock (2 levels) in 
'
9: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-http-0.24.3/lib/async/http/server.rb:69:in run' 8: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/endpoint.rb:46:inaccept'
7: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-http-0.24.3/lib/async/http/url_endpoint.rb:118:in bind' 6: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/host_endpoint.rb:55:inbind'
5: from C:/Ruby25/lib/ruby/2.5.0/socket.rb:227:in foreach' 4: from C:/Ruby25/lib/ruby/2.5.0/socket.rb:227:ineach'
3: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/host_endpoint.rb:56:in block in bind' 2: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:166:inbind'
1: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:110:in build' C:/Ruby25/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:168:inblock in bind': uninitialized constant Socket::SO_REUSEPORT (NameError)
Did you mean? Socket::SO_REUSEADDR

Requested to aske about the above line.

**Comment by ioquatix** [comment]
Thanks for the report, I've moved it to `async-io` where it's directly relevant.
