### ISSUE TITLE
Function not implemented - select_internal_with_gvl:epoll_wait

### ISSUE THREAD

**Issue by bobmaerten** [socketry/async#232]
I had this error on our server today, which is running ubuntu 22.04

```
  Function not implemented - select_internal_with_gvl:epoll_wait
```

**Backtrace (last few lines)**

```
lib/async/scheduler.rb:221 select
lib/async/scheduler.rb:221 run_once
lib/async/scheduler.rb:240 run
lib/kernel/async.rb:32 Async
```

**Comment by bobmaerten** [comment]
Apparently it triggered after we upgraded `io-event` gem to 1.2

**Comment by ioquatix** [comment]
The quick fix is to use io-event 1.1.x - or upgrade your kernel. What version of the kernel are you using?

**Comment by bobmaerten** [comment]
That's what I did to ensure deployability. We're running on Scalingo which is a French equivalent to Heroku.
`uname -a` in a remote console returns `5.4.0-107-generic #121-Ubuntu SMP`

**Comment by ioquatix** [comment]
This was fixed in v1.2.1 can you please confirm, thanks!

**Comment by trevorturk** [comment]
I was able to confirm that https://github.com/socketry/io-event/pull/59 fixes the issue for me on Heroku, at least.

**Comment by ioquatix** [comment]
Thanks for the update!

**Comment by ioquatix** [comment]
Actually, this is a different system call: ` IO_Event_Selector_EPoll_process_wait:pidfd_open`.

What kernel are you using? `pidfd_open` was introduced in 2019.

**Comment by ioquatix** [comment]
That kernel version is 10+ years old. We'd have to add conditional `pidfd_open` for these old kernels. Feel free to open a new issue.
