### ISSUE TITLE
transient task hangs

### ISSUE THREAD

**Issue by emiltin** [socketry/async#244]
I don't understand why this code never completes:

```ruby
require 'async'
Async transient:true do
  Async { sleep 1 }
end
```

**Comment by emiltin** [comment]
Using async 2.5.1, ruby 3.2.2

**Comment by ioquatix** [comment]
It looks like a bug.

**Comment by ioquatix** [comment]
I have a working repro/test case and know what the issue is, I'll try to release a fix tomorrow.

**Comment by emiltin** [comment]
Thank you for a quick fix 👍

**Comment by ioquatix** [comment]
Thanks for reporting it!
