### ISSUE TITLE
What's the correct way of doing recurrent timers?

### ISSUE THREAD

**Issue by dblock** [socketry/async#27]
I am looking for the equivalent of `every` in Celluloid. It was suggested to `loop` and `task.sleep`, however it doesn't behave the same way.

```ruby
  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "1: #{i}"
      task.sleep 3
    end
  end

  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "2: #{i}"
      task.sleep 3
    end
  end
```

```
1: 0
1: 1
1: 2
2: 0
2: 1
2: 2
```

that said, it works if both reactor runs are inside of a reactor

```ruby
::Async::Reactor.run do
  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "1: #{i}"
      task.sleep 3
    end
  end

  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "2: #{i}"
      task.sleep 3
    end
  end
end
```

```
1: 0
2: 0
1: 1
2: 1
1: 2
2: 2
```

Is the latter the correct way?

Maybe implementing a higher level timers API could be valuable? It would ensure to start a "parent" reactor, always behave like the second version, and have predictable (eg. not bail out on error) error behavior?

I also see https://github.com/socketry/async/blob/6b9b34e4c6182e04239a93916e33172533705913/lib/async/reactor.rb#L84.

```ruby
require 'async'

i = 0
j = 0

reactor = Async::Reactor.new

reactor.run do |task|
  reactor.every 3 do
    puts "1: #{i}"
    i += 1
  end

  reactor.every 3 do
    puts "2: #{j}"
    j += 1
  end
end
```

Works as expected. Does nothing without `reactor.run`. Maybe it just needs documentation and/or being wrapped and error out if not running under a reactor?

**Comment by ioquatix** [comment]
If you run it like this:

```ruby
  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "1: #{i}"
      task.sleep 3
    end
  end

  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "2: #{i}"
      task.sleep 3
    end
  end
```

You are running two sequential reactors and there is no interaction between the two.

```ruby
::Async::Reactor.run do
  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "1: #{i}"
      task.sleep 3
    end
  end

  ::Async::Reactor.run do |task|
    3.times do |i|
      puts "2: #{i}"
      task.sleep 3
    end
  end
end
```

is the correct way.

```
reactor.run do |task|
  reactor.every 3 do
    puts "1: #{i}"
    i += 1
  end

  reactor.every 3 do
    puts "2: #{j}"
    j += 1
  end
end
```

This way is risky because it doesn't run in a task context. You should probably avoid it.
