### ISSUE TITLE
Is is possible to run reactor's loop iteration by iteration manually?

### ISSUE THREAD

**Issue by graywolf-at-work** [socketry/async#28]
^ Title. Is it possible? Based on the code I assume not, but wanted to ask. If my analysis is correct (and it's not possible), would monkey-patching reactor to provide three new methods like (basically splitting `Reactor#run` into three methods)

```ruby
def setup(*args, &block)
  raise RuntimeError, 'Reactor has been closed' if @selector.nil?
  
  @stopped = false
  
  # Allow the user to kick of the initial async tasks.
  @initial_task = async(*args, &block) if block_given?
end

def loop_iter
  return if @stopped

  # running used to correctly answer on `finished?`, and to reuse Array object.
  @running, @ready = @ready, @running
  if @running.any?
    @running.each do |fiber|
      fiber.resume if fiber.alive?
    end
    @running.clear

    # if there are tasks ready to execute, don't sleep.
    if @ready.any?
      interval = 0
    else
      # The above tasks may schedule, cancel or affect timers in some way. We need to compute a new wait interval for the blocking selector call below:
      interval = @timers.wait_interval
    end
  end
  
  # - nil: no timers
  # - -ve: timers expired already
  # -   0: timers ready to fire
  # - +ve: timers waiting to fire
  if interval && interval < 0
    interval = 0
  end
  
  # Async.logger.debug(self) {"Updating #{@children.count} children..."}
  # As timeouts may have been updated, and caused fibers to complete, we should check this.
  
  # If there is nothing to do, then finish:
  if !interval && self.finished?
    return @initial_task
  end
  
  # Async.logger.debug(self) {"Selecting with #{@children.count} fibers interval = #{interval.inspect}..."}
  if monitors = @selector.select(interval)
    monitors.each do |monitor|
      monitor.value.resume
    end
  end
end

def teardown
  return @initial_task
ensure
  Async.logger.debug(self) {"Exiting run-loop because #{$! ? $!.inspect : 'finished'}."}
  @stopped = true
end
```

do mostly what I want? Calls would look something like (taken from README.md):

```ruby
begin
  reactor = Async::Reactor.new
  reactor.setup do
    socket = connect(remote_address) # May raise Async::Stop
    begin
      socket.write(...) # May raise Async::Stop
      socket.read(...) # May raise Async::Stop
    ensure
      socket.close
    end
  end
  loop do
    reactor.loop_iter
    # Do some of my own work
    break unless should_stop?
  end
ensure
  reactor.teardown
end
```

Would this work? I guess my main question is, will the `#loop_iter` here be noop if nothing is ready?

**Comment by ioquatix** [comment]
If you want to try this another way, you could probably do the following (untested):

```ruby
reactor = Async::Reactor.new

reactor.run do
    # ...
    reactor.stop
end
```

In the past, I've done something similar but there are sometimes useful variants like: `run_once`, `run_until(time)`, etc.

**Comment by graywolf** [comment]
`#run_once` would be great :) Thanks for the suggestion, this looks like I could avoid monkey-patching reactor all together, so will try it and see what it does. Thanks :)

**Comment by ioquatix** [comment]
The `#stop` solution might be the simplest and easiest solution to use rather than `#run_once`. Because it gives the flexibility to the user as to the stopping conditions (timeout, number of iterations). However, I'm not adverse to `#run_once` as long as it doesn't make the code more fragile.

One thing I'd like to understand is what `# Do some of my own work` is. In almost every case, you'd simply be better off scheduling a task or doing your own work on a separate thread. Is there some reason why this is useful/necessary?

**Comment by graywolf-at-work** [comment]
I want to use this project from ruby script for weechat. How that works is that I can register hooks to get my callback called every X ms (in my case probably 10, to be determined), "do my work" (in this case I would check if any data arrived and process them) and return from the callback. At that point weechat takes back the control and I'm waiting for another callback call.

However once I leave the ruby code, the GVL is locked and any background processing is therefore not possible since no thread can acquire GVL... This could possibly be solved somehow by modifying the weechat's ruby plugin (I don't know), but still, I would like to keep this singlethreaded :)

**Comment by ioquatix** [comment]
Ah yep.

I think in the first case, can you try using `#stop`. Can you report back whether that works or not? If not, let's see if we can find another solution (e.g. `#run_once`).

**Comment by ioquatix** [comment]
How is this working out for you?

**Comment by ioquatix** [comment]
Okay, there is an example how to do it with current interface.

**Comment by graywolf-at-work** [comment]
That indeed seems to work! Thank you very much :)

**Comment by ioquatix** [comment]
You are most welcome, let me know how you get on. The only thing I can think of is it might still make sense to have a "Run one iteration" function rather than the timer... but for now this is the simplest thing I can think of without digging into the code.
