### ISSUE TITLE
Support for TruffleRuby

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#29]
Following on from https://github.com/oracle/truffleruby/issues/1436 ...

We've migrated `timers` to us `Process.clock_gettime`. There might be other issues too.

You can run a large suite of tests by checking out the `async` source code and running:

`rake external`.

It will run specs for the following code bases: https://github.com/socketry/async/blob/de63b272bc17dc77da4ad0ea7a6a527643b4f95d/Rakefile#L25-L29

cc @jjyr @eregon

**Comment by ioquatix** [comment]
Also, I'd like to add support for travis testing across the entire eco-system, but we are currently blocking on https://github.com/travis-ci/travis-ci/issues/9803

**Comment by deepj** [comment]
I've tried to run a simple rack app on Falcon, but it failed on

```
$ ./config.ru
D, [2018-11-06T08:24:09.330000 #22009] DEBUG -- Async::IO::Socket: Binding to #<Addrinfo: 127.0.0.1:9292 TCP>
D, [2018-11-06T08:24:09.355000 #22009] DEBUG -- Async::IO::Socket: Binding to #<Addrinfo: [::1]:9292 TCP>
D, [2018-11-06T08:24:09.370000 #22009] DEBUG -- <Async::Reactor:0x6ee stopped=false>: Exiting run-loop because finished.
~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion': Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException) (RuntimeError)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.lang.RuntimeException.<init>(RuntimeException.java:80)
	from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
	from org.truffleruby.interop.RubyMessageResolution$ForeignToNativeNode.access(RubyMessageResolution.java:190)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:503)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:602)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:588)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode$TO_NATIVERootNode.execute(RubyMessageResolutionForeign.java:520)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext_ruby.rb:36:in `close'
	from ~/.gem/truffleruby/2.4.4/gems/async-1.10.3/lib/async/reactor.rb:208:in `close'
	from ~/.gem/truffleruby/2.4.4/gems/async-1.10.3/lib/async/reactor.rb:56:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command/serve.rb:97:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command/serve.rb:124:in `invoke'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command.rb:70:in `invoke'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/bin/falcon:26:in `<top (required)>'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `load'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `load'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `<main>'
```

To reproduce:

```ruby
run lambda {|env| [200, {}, ["Hello World"]]}
```

Then run it:

```
falcon --verbose serve -c the-script-above.rb
```

@eregon it ended it up in this issue https://github.com/oracle/truffleruby/issues/1441

**Comment by ioquatix** [comment]
What can I do to help resolve this issue? @eregon

**Comment by jjyr** [comment]
All specs run well on my machine after upgrade timers to 4.2.0, I'll make a PR after the Travis issue resolved.

**Comment by ioquatix** [comment]
I installed truffle ruby 1.0.0rc9 and tried to run specs for async on my laptop. Some pass, some fail, ran into the same `Message not supported: TO_NATIVE (UnsupportedMessageException)` error above.

**Comment by eregon** [comment]
@deepj  Could you report as a separate issue on the TruffleRuby bug tracker, to make it easier to track?

That `TO_NATIVE` error means a C extension is storing a Ruby object in native memory.
I guess that could be `nio4r`, which gets installed when installing `falcon`.
We'll need to dig deeper to see the actual place and see what can be done about it.
We're also currently investigating a general solution for this `TO_NATIVE` issues.

**Comment by eregon** [comment]
nio4r seems to have a pure-Ruby backend https://github.com/socketry/nio4r#supported-backends
That should work out of the box.
It looks like it can be used by setting `NIO4R_PURE=true`: https://github.com/socketry/nio4r/blob/e84f25ede87dcba8c52c9b86aa9bfbfbff0d9a59/lib/nio.rb#L17

@ioquatix What's the trade-off of using the pure-Ruby backend instead of the C extension? Should TruffleRuby try to support the C extension or there is no much advantage and just using the pure-Ruby backend is fine?

**Comment by deepj** [comment]
@ioquatix With `NIO4R_PURE=true` I can move futher. But `falcon` won't be working since it uses a forking model. So it stopped due this.

**Comment by ioquatix** [comment]
Can we make an extension to nio4r?

**Comment by ioquatix** [comment]
It already supports JRuby natively

**Comment by ioquatix** [comment]
You can start falcon using threaded model too.

**Comment by deepj** [comment]
@ioquatix How? I couldn't find anything about like that option in Falcon's README.md

**Comment by ioquatix** [comment]
—help and —threaded

**Comment by deepj** [comment]
I could move, it seems no issue from async gems perspective so far but I got this 
https://github.com/socketry/falcon/issues/33

**Comment by ioquatix** [comment]
<img width="668" alt="screen shot 2018-11-07 at 10 13 35 am" src="https://user-images.githubusercontent.com/30030/48094286-9c3c0e80-e276-11e8-8eab-a918c38f1b33.png">

Okay, it's working, I just release falcon v0.19.3

**Comment by ioquatix** [comment]
So, even though basic site is working, there are tons of issues.

- https://github.com/oracle/truffleruby/issues/1456
- https://github.com/oracle/truffleruby/issues/1457
- https://github.com/oracle/truffleruby/issues/1459
- https://github.com/oracle/truffleruby/issues/1460
- https://github.com/oracle/truffleruby/issues/1461

Most of these issues are relating to `async-io`.

I can't make progress until these issues are resolved.

**Comment by eregon** [comment]
@ioquatix Thank you for trying and filing the issues!
They seem relatively small problems, and so should be easy to fix :)

**Comment by ioquatix** [comment]
Please fix them and I will try again @eregon :)

**Comment by ioquatix** [comment]
@eregon I was just following up on this and noticed travis is broken again.

https://travis-ci.org/socketry/async/jobs/473835428

Is this something we can fix?

**Comment by eregon** [comment]
It's caused by https://travis-ci.community/t/new-gpg-key-for-rvm-releases/1521.
It's an issue between RVM and TravisCI, I cannot do much about it unfortunately.

**Comment by ioquatix** [comment]
https://github.com/rvm/rvm/issues/4561 is tracking the issue on RVM.

**Comment by ioquatix** [comment]
Currently TruffleRuby is mostly failing because of https://github.com/socketry/async/issues/37

**Comment by ioquatix** [comment]
All tests are now passing with TruffleRuby.

**Comment by picatz** [comment]
That's awesome @ioquatix 👏
