### ISSUE TITLE
Allow nested reactors/tasks, improves comparability of APIs

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#3]
It would be nice if something like `Reactor.run` was composable and provided some basic synchronisation when nested. This would be useful for having async APIs nest their own reactors, but use the parent's reactor if one was available.

**Comment by tarcieri** [comment]
Hierarchical selectors should be supportable with nio4r (both libev + Java NIO backends) but not necessarily tested yet

**Comment by ioquatix** [comment]
That's interesting - how would that work?

The problem right now is implementing a function like this:

```ruby
def run_server
    Reactor.run do
        TCPServer...
    end
end

Reactor.run
    #... nested function calls
        run_server
end
```

The idea being that you don't need to know how run_server is implemented, but within an existing reactor it's asynchronous. The benefits of this are composability - if you simply call `run_server`, it will work and block while it's working - use it from your top level script, or from a function, or whever, and it just works. But, if you drop it into a run-loop, it works async and doesn't block anything else.

**Comment by tarcieri** [comment]
You can add one selector to another as if it were any other selectable type. Hierarchical selectors are supported natively by various OS APIs such as epoll and kqueue.

**Comment by ioquatix** [comment]
That's awesome - but in order for that to work, we'd also need to support timers?

But I think it's an interesting idea to support in nio4r. Right now, it's not needed to achieve what I want here, I think I can just use the existing reactor if it exists.

**Comment by ioquatix** [comment]
Tasks are now nested using a tree structure.
