### ISSUE TITLE
Stopping remaining tasks upon completion of one task

### ISSUE THREAD

**Issue by ukazap** [socketry/async#302]
In scenarios where multiple tasks are running concurrently, and I need to stop all other tasks prematurely when one of them finishes; Is there a built-in mechanism or an established pattern within the async gem that would help address this use case?

**Comment by trevorturk** [comment]
I think this discussion may be of interest: https://github.com/socketry/async/discussions/292

**Comment by ukazap** [comment]
`Async::Waiter` seems to be what I’m looking for, unfortunately I’m stuck at Ruby 3.0.1. Would it be possible to backport?

**Comment by ioquatix** [comment]
I am not planning to backport anything to Async 1.x at this point, sorry.
