### ISSUE TITLE
Unexpected behaviour with Async::Wrapper.

### ISSUE THREAD

**Issue by huba** [socketry/async#32]
I am trying to catch some exceptions that might occur inside a task, this is related to [this issue](https://github.com/socketry/async-redis/issues/3#issuecomment-451360411) on async-redis. What I was trying to do essentially boils down to this
```ruby
Async.run do |main_task|
	begin
		Async.run do
			w = Async::Wrapper.new(File.open mytemp.path, 'r')

			w.wait_readable
			puts w.io.gets

			w.close

			raise ProtocolError
		end.wait
		# without #wait ProtocolError doesn't get caught at all
	rescue ProtocolError
		# This catches the exception, but it gets raised again. Somehow...
		puts "Rescuing from ProtocolError"
	end
end
```

Note `ProtocolError` is just a subclass of `StandardError`. I expected the output of this to be,
```
the first line from the file
Rescuing from ProtocolError
```
However I got,
```
the first line from the file
Rescuing from ProtocolError
Traceback (most recent call last):
        1: from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:74:in `block in initialize'
./test.rb:24:in `block (2 levels) in <main>': ProtocolError (ProtocolError)
```
The exception was caught and handled, yet it still makes the program exit with an error? This happens no matter where I raise `ProtocolError` inside the child task after the file is opened and wrapped.

This gets weirder when I start more sub-tasks with io in the same reactor. In light of what I described so far I would expect it to crash before finishing the first one, yet that's not what happens.
```ruby
Async.run do |main_task|
	3.times do |n|
		begin
			puts "Read #{n}"
			Async.run do
				puts "Task #{n}"
				w = Async::Wrapper.new(File.open mytemp.path, 'r')

				w.wait_readable
				puts w.io.gets

				w.close

				raise ProtocolError
			end.wait
			# without #wait ProtocolError doesn't get caught at all
		rescue ProtocolError
			# This catches the exception, but it gets raised again. Somehow...
			puts "Rescuing from ProtocolError"
		end
	end
end
```
The result is,
```
Read 0
Task 0
first line of the file
Rescuing from ProtocolError
Read 1
Task 1
Read 2
/usr/lib/ruby/2.5.0/set.rb:349:in `add': can't add a new key into hash during iteration (RuntimeError)
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/node.rb:87:in `parent='
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/node.rb:36:in `initialize'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:61:in `initialize'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/reactor.rb:95:in `new'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/reactor.rb:95:in `async'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/reactor.rb:49:in `run'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async.rb:28:in `run'
	from ./test.rb:18:in `block (2 levels) in <main>'
	from ./test.rb:15:in `times'
	from ./test.rb:15:in `block in <main>'
	from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:74:in `block in initialize'
```
Again, this does not happen if the io is removed from the inner task. My next step I suppose is to enable debug output and/or step through with a debugger.

**Comment by ioquatix** [comment]
Exception handling for a task is done here:

https://github.com/socketry/async/blob/04abbf3eb82985e362e0adfadb18012a1945644b/lib/async/task.rb#L73-L89

When a task runs synchronously, the exception will bubble up as you expect. But when the task is resumed by the reactor, it will bubble up through `Async::Reactor#run`. Once a task invokes some asynchronous behaviour, it is not possible for the parent task to catch the exception without invoking a synchronisation primitive, e.g. `#wait`.

```ruby
Async.run do |task|
	puts "A"
	Async.run do |subtask|
		puts "B"
		subtask.sleep 1
		puts "C"
		raise ArgumentError, "Foo bar"
	end # try adding .wait here and see the different order of operations.
	puts "D"
end
```

**Comment by huba** [comment]
@ioquatix that makes sense, I did step through the exception handling with a debugger which was helpful. Where I'm having trouble is when there is wrapped io inside the sub-task.
The first example I gave uses `#wait` to synchronize the sub-task and the exception gets caught correctly, that is the code in the `rescue` block is executed, however the exception gets raised again somehow and the program exits with an error. Like so,
```
the first line from the file
Rescuing from ProtocolError
Traceback (most recent call last):
        1: from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:74:in `block in initialize'
./test.rb:24:in `block (2 levels) in <main>': ProtocolError (ProtocolError)
```
Here is the output with `$DEBUG` set,
```
first line of the file
Exception `ProtocolError' at test.rb:24 - ProtocolError
D, [2019-01-09T13:49:42.951173 #4062] DEBUG -- <Async::Task:0x2ac63f7c9bf8 status=failed>: ProtocolError (ProtocolError)
test.rb:24:in `block (2 levels) in <main>'
/home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:74:in `block in initialize'
Exception `ProtocolError' at /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:85 - ProtocolError
Exception `ProtocolError' at /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:51 - ProtocolError
Rescuing from ProtocolError
Exception `ProtocolError' at /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/wrapper.rb:63 - ProtocolError
D, [2019-01-09T13:49:42.951273 #4062] DEBUG -- <Async::Reactor:0x2ac63f7c9f2c stopped=false>: Exiting run-loop because #<ProtocolError: ProtocolError>.
Traceback (most recent call last):
        1: from /home/huba/.gem/ruby/2.5.0/gems/async-1.12.0/lib/async/task.rb:74:in `block in initialize'
test.rb:24:in `block (2 levels) in <main>': ProtocolError (ProtocolError)
```
I don't understand why the exception gets raised again after it is handled by the `rescue` block outside the task. This only happens when there is an `Async::Wrapper` inside the task.

**Comment by ioquatix** [comment]
I see what is going on.

The exception is being raised twice because when the exception is thrown, it triggers the ensure block via the re-raise:

https://github.com/socketry/async/blob/04abbf3eb82985e362e0adfadb18012a1945644b/lib/async/task.rb#L85

That invokes `finish!` which causes the waiting task to resume:

https://github.com/socketry/async/blob/04abbf3eb82985e362e0adfadb18012a1945644b/lib/async/task.rb#L191

That waiting task which is calling `#wait` then gets the exception raised:

https://github.com/socketry/async/blob/04abbf3eb82985e362e0adfadb18012a1945644b/lib/async/task.rb#L139

This invokes `Condition#wait` which invokes `Task.yield`:

https://github.com/socketry/async/blob/04abbf3eb82985e362e0adfadb18012a1945644b/lib/async/condition.rb#L37

When the exception is passed back, it get's thrown on the waiting task/thread.

Then, when that is all done, the first raise propagates back up to the reactor and that is reported.

I'll think about how to fix this or at least make it more intuitive. One option would be to remove the `raise` here:

https://github.com/socketry/async/blob/master/lib/async/task.rb#L85

Or maybe just `raise unless @finished`.

One other option to consider is whether exceptions should propagate between tasks. A task is like a promise, so I think it's okay. However, I don't want exceptions to vanish into thin air, if no one is waiting on a task... it's a problem.

**Comment by ioquatix** [comment]
Here is the commit: https://github.com/socketry/async/commit/49c07049d5c9be87b58b23226f9e6674fdc8a67e

I haven't released it yet, because I need to figure out if it is a good change. I think it is, but I'm not certain of it.

**Comment by ioquatix** [comment]
After playing around with it, it caused a regression in falcon. Because `SignalException` was getting swallowed. I decided that `Exception` should go straight up.

Implemented in b9775b300730925cb0829bba801e4876dfb65e1e

**Comment by ioquatix** [comment]
With the updated code:

```
require 'async'

Async.run do
	Foo.new
end
```

Fails but no error is reported.

You need to write:

```
require 'async'

Async.run do
	Foo.new
end.wait
```

I'm not sure if this is good behaviour. At worst, you write code that fails without realising it because the exception isn't propagated up.

**Comment by ioquatix** [comment]
Also, calling `#wait` isn't always the ideal solution because it also forces synchronisation.

One option is to log exceptions, but that could get annoying if that's part of what you want to do. Right now, exceptions are logged at `debug` level.

**Comment by ioquatix** [comment]
One other option would be to make a special class of exception that can go between task boundaries, e.g.

```ruby
class Async::Failure
end

# ...
				begin
					@result = yield(self, *args)
					@status = :complete
					# Async.logger.debug("Task #{self} completed normally.")
				rescue Failure => error
					# General errors cause the task to enter the failed state.
					@result = error
					@status = :failed
					Async.logger.debug(self) {$!}
				rescue Stop
					@status = :stop
					# Async.logger.debug("Task #{self} stopped: #{$!}")
					Async.logger.debug(self) {$!}
				rescue Exception
					# Exceptions (like SignalError) immediately terminate the task/run-loop.
					@status = :exception
					Async.logger.debug(self) {$!}
					raise
				ensure
					# Async.logger.debug("Task #{self} closing: #{$!}")
					finish!
				end
# ...
```

**Comment by ioquatix** [comment]
So, your `ProtocolError` would need to be `class ProtocolError < Async::Failure` which would allow it to transit between tasks without being logged or raised.

**Comment by huba** [comment]
Having to call `#wait` is definitely not a good solution, in that case you might as well rename the gem to `sync`. Having a special class of exceptions is not such a great solution, but I agree that it's probably the best one available.

**Comment by ioquatix** [comment]
The biggest usability problem is a program which fails but does not report that failure. So we need to avoid that. Actually having exception handling at the task level is kind of odd, but necessary to do some basic stuff like stopping tasks. The question then becomes what exceptions should trigger a task to enter the failed state, and what exceptions should propagate up. It probably needs to be an explicit decision.

**Comment by ioquatix** [comment]
Okay, what appears to be my final solution is this:

- Tasks behave like promise and capture all exceptions.
- Exceptions are logged according to whether `#wait` was invoked or not. If `#wait` was not invoked, is is logged at level `error`, otherwise it is logged at level `debug`. (so always logged or captured).
- StandardError don't propagate, but Exception does.

May need to consider making TimeoutError a subclass of Exception.
