### ISSUE TITLE
Sidekiq shutdown issue

### ISSUE THREAD

**Issue by pineman** [socketry/async#321]
Hi!

Thank you for all the work in async ruby 😄 

I'm facing an issue using async in sidekiq. My tasks return `nil` when sidekiq exits via SIGTERM.
From what I've been able to piece together, I believe this is what's happening:
* Sidekiq [raises](https://github.com/sidekiq/sidekiq/blob/efd152a663689965f9a6426e6c3e918ad347ac58/lib/sidekiq/processor.rb#L57) `Sidekiq::Shutdown` in worker threads ([which inherits](https://github.com/sidekiq/sidekiq/blob/efd152a663689965f9a6426e6c3e918ad347ac58/lib/sidekiq.rb#L145) from `Interrupt`)
* This causes async [to `stop` the reactor](https://github.com/socketry/async/blob/f5252765f1393fb8af3c73b6da21c2d6341e3dce/lib/async/scheduler.rb#L362)
* However, it seems like `Sidekiq::Shutdown` is not propagated to the job outside Async (i.e., it's not re-raised).
  * My expectation would be for `Sidekiq::Shutdown` to be re-raised in the "synchronous" job context, so that the job's execution would halt immediately and sidekiq may rescue it. Otherwise, job execution proceeds with tasks having a return value of `nil`.

I can currently workaround this by raising `Sidekiq::Shutdown` myself when I detect the tasks' return value is `nil` (as I don't expect that to be ever be a valid return value in my code).

Sample code of my sidekiq job:
```
class HardJob
  include Sidekiq::Job

  def perform
    resp1, resp2 = Async do
      [Async { req }, Async { req }].map(&:wait)
    end.wait
    puts "tasks returned nil!" if resp1.nil? && resp2.nil?
  end
  
  def req
    uri = URI("https://httpbin.org/delay/10")
    Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
      http.request(Net::HTTP::Get.new(uri))
    end
  end
end
```
[Here's a fresh rails project](https://github.com/pineman/shutdown) that reproduces the issue, if it helps.
To reproduce:
 * run sidekiq with a low `-t` option, like `bundle exec sidekiq -t 3`
 * wait for sidekiq to start processing the job
 * quickly send SIGTERM to sidekiq's pid while the request task is still running
 * see that `tasks returned nil!` is printed - meaning the job should've been interrupted, but it proceeded instead

Any insight would be greatly appreciated! Cheers!

**Comment by ioquatix** [comment]
I think I know what's going on here, let me see if I can fix it.

**Comment by ioquatix** [comment]
Can you please try release v2.12.1 to see if it fixes the issue? Thanks!

**Comment by pineman** [comment]
Yes, it does! Thanks so much for the quick fix 😄

**Comment by ioquatix** [comment]
No problem, thanks for the detailed report, it allowed me to figure out the issue quickly.
