### ISSUE TITLE
`system` hangs if file does not exist

### ISSUE THREAD

**Issue by cretz** [socketry/async#351]
If you run `system` inside `Async` with a non-existent executable on Linux with Ruby 3.3 it hangs. This behavior is confirmed in 2.17.0 and 2.18.0 (I didn't check any earlier than that).

This synchronous code works:

```ruby
puts "Running on: #{RbConfig::CONFIG['host_os']}"
res = system 'echo', 'hello'
puts "Result 1: #{res}"
res = system 'does-not-exist', 'hello'
puts "Result 2: #{res}"
```

And outputs:

```
Running on: linux
hello
Result 1: true
Result 2:
```

But this code does not:

```ruby
require 'async'

Async do
  puts "Running on: #{RbConfig::CONFIG['host_os']}"
  res = system 'echo', 'hello'
  puts "Result 1: #{res}"
  res = system 'does-not-exist', 'hello'
  puts "Result 2: #{res}"
end
```

This hangs on the second `system` call. This was discovered after a deep dive of why `Minitest` `assert_equal` was hanging. It turns out, Minitest uses `diff` on the system when reporting an `assert_equal` failure, but first checks for `gdiff` which we don't have, ref: https://github.com/minitest/minitest/blob/e4417c5b13ab917a60c218700041152136bc07c8/lib/minitest/assertions.rb#L33. So we have to `Minitest::Assertions.diff = 'diff'` to get `Async`-based tests to not break here.

(sorry if this is already reported, I could not find an issue)

**Comment by ioquatix** [comment]
Nice find. I didn't know about this! haha.

![image](https://github.com/user-attachments/assets/174b916f-7bab-4d0d-96ee-d24fd8045ece)

I'll investigate the issue today.

**Comment by ioquatix** [comment]
I could not reproduce from the given example.

```
samuel@aiko ~/D/s/async (main)> ruby --version
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
samuel@aiko ~/D/s/async (main)> cat ./test.rb
#!/usr/bin/env ruby

require "async"

Async do
	puts "Running on: #{RbConfig::CONFIG['host_os']}"
	res = system 'echo', 'hello'
	puts "Result 1: #{res.inspect}"
	res = system 'does-not-exist', 'hello'
	puts "Result 2: #{res.inspect}"
end
samuel@aiko ~/D/s/async (main)> bundle exec ./test.rb
Running on: linux
hello
Result 1: true
Result 2: nil
```

Can you confirm I've got the correct reproduction script?

**Comment by ioquatix** [comment]
I tried to reproduce the original error but couldn't:

```ruby
#!/usr/bin/env ruby

require "minitest/autorun"
require "async"

class Test < Minitest::Test
	BIG_TEXT_A = "The quick brown fox jumps over the lazy dog.\n" * 10
	BIG_TEXT_B = BIG_TEXT_A.dup.sub("quick", "slow")
	
	def test_diff
		Async do |task|
			assert_equal(BIG_TEXT_A, BIG_TEXT_B)
		end
	end
end
```

I added some instrumentation to the scheduler `process_wait` hook:

```ruby
		# Wait for the specified process ID to exit.
		# @parameter pid [Integer] The process ID to wait for.
		# @parameter flags [Integer] A bit-mask of flags suitable for `Process::Status.wait`.
		# @returns [Process::Status] A process status instance.
		# @asynchronous May be non-blocking..
		def process_wait(pid, flags)
			return @selector.process_wait(Fiber.current, pid, flags).tap{|result|
				Fiber.blocking{$stderr.puts "process_wait(#{pid}, #{flags}) -> #{result.inspect}"}
			}
		end
```


It appears to work okay:

```
> bundle exec ./test.rb
Run options: --seed 20496

# Running:

process_wait(927854, 0) -> #<Process::Status: pid 927854 exit 127>
process_wait(927855, 0) -> #<Process::Status: pid 927855 exit 0>
process_wait(927856, 0) -> #<Process::Status: pid 927856 exit 1>
F

Finished in 0.002793s, 358.0683 runs/s, 358.0683 assertions/s.

  1) Failure:
Test#test_diff [test.rb:12]:
--- expected
+++ actual
@@ -1,4 +1,4 @@
-"The quick brown fox jumps over the lazy dog.
+"The slow brown fox jumps over the lazy dog.
 The quick brown fox jumps over the lazy dog.
 The quick brown fox jumps over the lazy dog.
 The quick brown fox jumps over the lazy dog.


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by ioquatix** [comment]
Is it possible something in your test suite is monkey patching `Kernel::system`?

**Comment by cretz** [comment]
Interesting, this is breaking for me:

```
cretz@DESKTOP-W0A14BL:~/work/tem/sdk-ruby/temporal-sdk-ruby/temporalio$ cat ./test.rb
require 'async'

Async do
  puts "Running on: #{RbConfig::CONFIG['host_os']}"
  res = system 'echo', 'hello'
  puts "Result 1: #{res}"
  res = system 'does-not-exist', 'hello'
  puts "Result 2: #{res}"
end
cretz@DESKTOP-W0A14BL:~/work/tem/sdk-ruby/temporal-sdk-ruby/temporalio$ bundle exec ruby --version
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]
cretz@DESKTOP-W0A14BL:~/work/tem/sdk-ruby/temporal-sdk-ruby/temporalio$ bundle exec ruby ./test.rb
Running on: linux
hello
Result 1: true
```

It hangs right there. I am not doing any monkey patching. This was also hanging for me inside of a GitHub action for Ubuntu and Ruby 3.3 (but not 3.1 I don't think). I will do some more investigation, possibly including a simple repository that replicates the issue with a simple GitHub action, and get back.

**Comment by olleolleolle** [comment]
I was also able to make it hang on that.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'async'
end

Async do
  puts "Running on: #{RbConfig::CONFIG['host_os']}"
  res = system 'echo', 'hello'
  puts "Result 1: #{res}"
  res = system 'does-not-exist', 'hello'
  puts "Result 2: #{res}"
end
```

See [Bundler inline docs](https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html).

**Comment by ioquatix** [comment]
lol, I cannot reproduce, I tried `IO_EVENT_BACKEND=Select` too.

Okay, can you please tell me:

- `uname -a`
- `ruby -v`
- Your shell and version of shell.

**Comment by ioquatix** [comment]
For me it's:

```
samuel@aiko ~/D/tmp> uname -a
Linux aiko 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux
samuel@aiko ~/D/tmp> ruby -v
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]
samuel@aiko ~/D/tmp> $SHELL -v
fish, version 3.7.1
```

**Comment by ioquatix** [comment]
In Async v2.19, I've introduced more debug output: https://socketry.github.io/async/releases/index#async::scheduler-debugging

Can one of you run the hanging example with `CONSOLE_LEVEL=debug` environment variable set, and show me the full output?

Thanks.

**Comment by ioquatix** [comment]
This appears to be a problem in Ruby `process.c` which can fork with an active scheduler without cleaning up correctly. I think at best we can fix this in Ruby 3.4 and maybe backport the fix. I'll need to investigate further.

**Comment by ioquatix** [comment]
See https://github.com/ruby/ruby/pull/12052 for a possible fix.

**Comment by ioquatix** [comment]
Okay, I believe I've found the root cause, a race condition in the process wait code.

**Comment by ioquatix** [comment]
I've released `io-event` v1.7.4 which appears to fix this issue. Please let me know if you are still having issues.

**Comment by sonicdes** [comment]
I'm still seeing this problem, but it seems to apply to all `system` calls instead of only illegal commands as originally described here. It happens after calling `system` twice within a single Async task.

```ruby
RUBY_VERSION
=> "3.3.6"

IO::Event::VERSION
=> "1.7.4"

IO::Event::Selector.default
=> IO::Event::Selector::EPoll

Async { 2.times { system "echo #{_1}" } }
0
1
^C # Hangs here with the second spawned process in Zombie state

Async { 2.times { system "fakeecho #{_1}" } }
=> #<Async::Task:0x0000000000028334>
# Calling illegal commands no longer triggers a hang
```

This only happens when EPoll selector is used, and not with io_uring.

**Comment by ioquatix** [comment]
Thanks for your report I’ll investigate it.

**Comment by ioquatix** [comment]
I was able to reproduce the issue: https://github.com/socketry/io-event/pull/126

**Comment by ioquatix** [comment]
It looks like `epoll_ctl` is not re-arming the file descriptor, as the `pidfd` returns the same fd (7 in this case). Adding a small sleep causes the example to work, e.g.:

```
Waiting for process 43141
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x7acd18fde710, waiting->events=1 (currently waiting for 0)
IO_Event_Selector_EPoll_Descriptor_update:epoll_ctl: descriptor=7, operation=1, events=25
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x7acd18fde710, waiting->events=1 (currently waiting for 1) result=1
Waiting for process 43141, fd=7
0
Process 43141 exited
true
Waiting for process 43142
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x7acd18fde710, waiting->events=1 (currently waiting for 0)
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x7acd18fde710, waiting->events=1 (currently waiting for 1) result=0
Waiting for process 43142, fd=7
1
```

vs

```
Waiting for process 43774
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x77ab613de710, waiting->events=1 (currently waiting for 0)
IO_Event_Selector_EPoll_Descriptor_update:epoll_ctl: descriptor=7, operation=1, events=25
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x77ab613de710, waiting->events=1 (currently waiting for 1) result=1
Waiting for process 43774, fd=7
0
Process 43774 exited
true
Waiting for process 43775
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x77ab613de710, waiting->events=1 (currently waiting for 0)
IO_Event_Selector_EPoll_Descriptor_update:epoll_ctl: descriptor=7, operation=1, events=25
IO_Event_Selector_EPoll_Waiting_register: descriptor=7, waiting=0x77ab613de710, waiting->events=1 (currently waiting for 1) result=1
Waiting for process 43775, fd=7
1
Process 43775 exited
true
```

**Comment by ioquatix** [comment]
Okay, I found the root cause: https://github.com/socketry/io-event/pull/126

**Comment by ioquatix** [comment]
Can you please try `io-event` v1.7.5 - this issue should be fixed.

**Comment by sonicdes** [comment]
Yes, it is fixed now. Thanks a lot for your work!

**Comment by ioquatix** [comment]
Thanks for reporting the issue!
