### ISSUE TITLE
Function not implemented - IO_Event_Selector_EPoll_process_wait:pidfd_open

### ISSUE THREAD

**Issue by fwininger** [socketry/async#366]
Follow this comment : https://github.com/socketry/async/issues/232#issuecomment-1736386315

I open a issue because we also have the follow error `Function not implemented - IO_Event_Selector_EPoll_process_wait:pidfd_open` on kernel 4.18.0-553.16.1.el8_10.x86_64 (Redhat 8)

After investigate, pidfd_open was introduced on [kernel 5.3](https://man7.org/linux/man-pages/man2/pidfd_open.2.html)

Could you please add conditional for old kernel ?

**Comment by ioquatix** [comment]
Linux kernel 4.18 is almost 7 years old.

What kind of conditional are you thinking of?

**Comment by ioquatix** [comment]
I investigated this further. I don't think there is any good alternative for event driven process wait, except using a thread pool or some other overly complex contraption.

**Comment by fmang** [comment]
Thank you for your answer.

We do not have control over the running system, but if supporting old kernels would not be reasonable for io-event we’re open to workarounds. io-event not defaulting to a blocking wait call is fine, but is there a way to explicitly call the blocking wait from user code when deadlocks are improbable?

**Comment by ioquatix** [comment]
Something that will work in recent Ruby versions (IIRC 3.2+) is the following:

```ruby
Fiber.blocking do
  Process.wait(...)
end
```

This will prevent the fiber scheduler from intercepting the `process_wait`.

**Comment by fwininger** [comment]
@ioquatix thanks for your time and for your answer. We are going with the proposed solution.

I close the issue.
