### ISSUE TITLE
NameError: no method to_str

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#37]
I'm trying to figure out why this is failing:

```
38.87s: <Async::Task:0x6df8 failed> [pid=8615]
      |   NameError: no method to_str
      |   → /home/travis/.rvm/rubies/truffleruby-1.0.0-rc13/lib/truffle/truffle/cext.rb:941 in `special_form'
      |     /home/travis/.rvm/rubies/truffleruby-1.0.0-rc13/lib/truffle/truffle/cext.rb:941 in `rb_funcall'
      |     /home/travis/build/socketry/async/vendor/bundle/truffleruby/2.4.0/gems/nio4r-2.3.1/ext/nio4r/selector.c:282 in `NIO_Selector_synchronize'
      |     /home/travis/build/socketry/async/vendor/bundle/truffleruby/2.4.0/gems/nio4r-2.3.1/ext/nio4r/selector.c:310 in `NIO_Selector_register'
```

Here is the C code:

https://github.com/socketry/nio4r/blob/master/ext/nio4r/selector.c#L273-L291

Here is TruffleRuby code:

https://github.com/oracle/truffleruby/blob/master/lib/truffle/truffle/cext.rb#L937-L944

cc @eregon

**Comment by eregon** [comment]
@ioquatix Could you report this issue at https://github.com/oracle/truffleruby/issues ?
That makes it easier to track and means other people of the team can work on it :smiley:

**Comment by eregon** [comment]
In other words, this is most likely a TruffleRuby bug, and generally almost any behavior different from MRI is a bug.

**Comment by ioquatix** [comment]
I did wonder if it's a bug in how the C code works.

**Comment by ioquatix** [comment]
It looks like this might be working now, but there are other issues.

https://travis-ci.org/socketry/async/jobs/513351431
