### ISSUE TITLE
Policy for supporting EOL Ruby

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#39]
@ganmacs Looks like this is all good now: https://travis-ci.org/socketry/async-http/builds/556647690

Bearing in mind, I want to establish some policy on deprecation of EOL Ruby.

Can you give me some ideas since this seems important to you.

**Comment by ganmacs** [comment]
Thank you for your great help.

Our rough plan is here https://github.com/fluent/fluentd/issues/2380#issuecomment-485058134 (Sorry, it has not decided exactly and it does not mean we expect that socketry/asyn supports EOL Ruby same as fluentd. it's jsut FYI).

**Comment by ioquatix** [comment]
Thanks for this. I'm not sure I can realistically support older rubies if it becomes a huge maintenance burden because I'm not receiving any compensation for this work, and I don't personally care about old Rubies.

That being said, as long as things keep on working, the only time it would break is when I start using new functionality which is not supported in older Rubies. e.g. `&.` operator.

Even if that happens, the existing versions of Async and all dependencies should continue to work. I'll try to formalise this policy into the README so that there is clarity for everyone involved. Thanks for a link to your current policy, it is well researched.

**Comment by ioquatix** [comment]
My plan is to incrementally deprecate support for EOL rubies when making new minor releases.
