### ISSUE TITLE
Stopping tasks and nested tasks

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#4]
The initial design of async, didn't track nested tasks. This means that when you stop the parent task, async blocks started in that task wouldn't also be stopped, they'd keep on running. I found in async-dns this wasn't really great - it made it cumbersome to keep track of execution state and stop things.

Ideally, when stopping a task, you kill that task, and any child async blocks. The implications of this, is that if you have a TCP server, and it has spawned a number of children tasks, when you kill the server you also kill all the children. I think this is the right design, but in theory you could also detach a child task from it's parent so it would continue on unimpeded. However, the machinery for stopping tasks needs to be robust in the face of complex user code, without the user having to track a lot of state.

**Comment by ioquatix** [comment]
@tarcieri I'd love to have your feedback on this and whether you think it's sane. It will simplify upstream code a lot, and it also has the potential to improve the reliability of systems which are composed together.

**Comment by tarcieri** [comment]
I definitely think this is great and important. On JRuby, since Fibers are backed by JVM threads if you don't terminate them you wind up leaking threads /cc @headius
