### ISSUE TITLE
question, Make a promise/future like code with async

### ISSUE THREAD

**Issue by kinnrot** [socketry/async#40]
Is it possible to wrap up the code with tasks and make it look synchronized? Something similar to synchrony? Or await in JavaScript? Let's say my server gets a request, execute some async io , release his fiber to other consumers, when get result from async it publish a domain event , the controller need to do a non blocking wait to this domain event. Is it something this library can do ? I'm looking for something similar to "run a command , subscribe to possible events that command should fire, without blocking"

**Comment by ioquatix** [comment]
It sounds like you are asking for something that is exactly why this library was created, so I think the best thing is fo your you to try it out. You can call `Task#wait` and it behaves like a future.

**Comment by ioquatix** [comment]
> subscribe to possible events that command should fire

You can use `Async::Queue`.

**Comment by kinnrot** [comment]
The fundamental problem with task wait is that when you subscribe to event
inside a task , the task completes , fit doesn't know to wait for an
event... I'm sure it's possible but not sure about the right way to write
it down.

**Comment by kinnrot** [comment]
Yeah that sounds like a good idea will do, just to be clear, should I do
queue#pop inside a task , it'll unblock until something is in the queue?

**Comment by ioquatix** [comment]
Yes. Here is an example: https://github.com/socketry/async/blob/master/examples/queue/producer.rb
