### ISSUE TITLE
ConditionVariable functionality?

### ISSUE THREAD

**Issue by emiltin** [socketry/async#44]
How would you use async to wait for a condition, with a timeout, like ConditionVariable?
E.g. make a task sleep until a counter reach a certain value, or the until the timeout is reached?

**Comment by ioquatix** [comment]
- `Async::Condition` (direct fiber.resume)
- `Async::Notification` (indirect resume via event loop)
- `Async::Queue` (multiple items, unlimited length)
- `Async::LimitedQueue` (multiple items, fixed length, producer/consumer).

**Comment by emiltin** [comment]
Great, thanks.

**Comment by emiltin** [comment]
Working example:
```ruby
require 'async'

Async do |task|
	condition = Async::Condition.new
	Async do |subtask|
		subtask.with_timeout(2) do
			puts 'waiting for condition'
			v = condition.wait
			puts "got #{v}"
		rescue Async::TimeoutError
			puts 'timeout'
		end
	end
	
	task.sleep rand(3)+1
	condition.signal(842552)
end
```
