### ISSUE TITLE
using rspec to test async based server

### ISSUE THREAD

**Issue by emiltin** [socketry/async#49]
I have a server class based on async-io. This server class is used to test external clients, using RSpec.

Because the site connects to the sever (not the other way around) and this includes a delay, I want to keep the server running across tests. But unless I stop the reactor at the end of each test, it blocks and no more tests are run. The way I've tried to solve this is to start and stop the reactor for each test, essentially:

```
reactor.run do |task|
  # run the test
  reactor.stop
end
```

But it seems reactor.stop is rather slow. Is there a better way to achieve what I want?

**Comment by ioquatix** [comment]
Async is designed this way to ensure tests and code is isolated.

The only way you can work around this is by using `async-container` and maintaining the server in a background thread/process.

**Comment by emiltin** [comment]
Ok. But is the pattern of starting/stopping the reactor otherwise ok, apart from being somewhat slow?

**Comment by emiltin** [comment]
If I keep the server in a separate thread/process then I will not be able to use async conditions in my server to wait for e.g. connections or packages, but would instead have to rely on normal thread tools like semaphores, queues, etc?

**Comment by ioquatix** [comment]
> Ok. But is the pattern of starting/stopping the reactor otherwise ok, apart from being somewhat slow?

It shouldn't be slow. What is slow?

**Comment by ioquatix** [comment]
You can make 32,000 top level `Async{}` calls per second. It's not super fast, but it's not slow either.

```ruby
Benchmark.ips do |x|                                                                                                                                                            
	x.report("Async{}", "Async{}")                                                                                                                                                
end                                                                                                                                                                             

Warming up --------------------------------------
             Async{}     3.118k i/100ms
Calculating -------------------------------------
             Async{}     32.663k (± 7.2%) i/s -    165.254k in   5.090684s
```

**Comment by emiltin** [comment]
It seems to be when the reactor.run() block ends:

```
reactor = Async::Reactor.new
start = stop = nil

reactor.run do |task|
  # perform rspec test here, involving sockets and conditions...
  reactor.stop
  start = Time.now
end
stop = Time.now

puts "#{stop-start}s" => # 0.101104s
```

If I don't perform any thing in the rspec test, it's not slow. Guess it must be related to sockets or conditions having to be stopped?

**Comment by ioquatix** [comment]
On my computer it's 10x faster - but of course we just comparing specific systems. That being said, I'm definitely keen to make things faster if you see some obvious issue.

```
[64] pry(main)> puts "#{stop-start}s"                                                                                                                                                          
0.018555s
```

I wonder why it's slower on your system. I will check on my linux server.

**Comment by emiltin** [comment]
The test sends a request and waits for a response. That ends up waiting for an async condition. If I comment out this line 

`@condition.wait`

The time goes down to about 0.00001.

**Comment by emiltin** [comment]
In fact's in a Notification, not a condition

**Comment by ioquatix** [comment]
Can you give me a short repro/example?

**Comment by ioquatix** [comment]
Sorry I didn’t completely understand you before.

**Comment by emiltin** [comment]
Sent you an invite to a repo that shows the issue. To run:
`$ bundle exec ruby test.rb to `

**Comment by ioquatix** [comment]
I'm taking a look now.

**Comment by ioquatix** [comment]
Between the time you call `reactor.stop` and the reactor actually stops, you end up handling some network IO. Try printing out the packet from the connector packet receive loop.

The reason why this happens might be an artifact of how the run-loop works and checks @stopped:

```
			@timers.wait do |interval|
				# run loop
			end until @stopped
```

Because of this, @timers.wait yields multiple times, if there are no timers, it then loops because `until @stopped`. If you set `@stopped` to false, it won't cause the run-loop to exit until there are no timers.

I guess this is a bug.

**Comment by emiltin** [comment]
Glad if the repo was of some use.

**Comment by ioquatix** [comment]
Okay, there is a fix for this inbound.
