### ISSUE TITLE
Per-fiber annotations

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#5]
I've been thinking it would be nice to have some kind of per-fiber annotation - e.g. what it's currently doing (e.g. `:sleeping`, `:wait_readable`, etc), like a process title. it would help with debugging. I'm just not sure if it's a good idea from the POV of overhead. Perhaps having a mixin which provides debugging functionality which is only loaded if `$DEBUG` is set..?

**Comment by ioquatix** [comment]
I've been thinking about this, and I think it makes most sense to keep this out of the direct implementation of this gem. I'd like to think we can have a debug module prepended into the reactor which annotates fibers using a fiber-local variable, e.g. 

```ruby
def sleep
    Thread.current[:async_annotation] = "sleeping for #{duration}"
    super
end
```

We can apply this logic everywhere, it could even be within specific code, e.g.

```ruby
def resolve(name)
    Task.annotate{"resolving #{name}"}
    # ....
end
```

One option would be to consider using the last thing logged, e.g. make a custom log formatter, which saves the last log at level `info` to the annotation. Something to explore a bit more.

**Comment by tarcieri** [comment]
Celluloid subclassed `Fiber` and added some attributes to it for this sort of thing, FWIW
