### ISSUE TITLE
CI: Drop Travis CI for GitHub Actions

### ISSUE THREAD

**Issue by olleolleolle** [socketry/async#60]
I note that there are two CI configured, and that perhaps Travis has more elements to its matrix. GitHub Actions is faster.

- Is there overlap?
- Can some elements be dropped from Travis?

---

- will use https://github.com/ruby/setup-ruby

**Comment by ioquatix** [comment]
- Use `ruby/setup-ruby`.
- Test on more platforms.
- Don't care about < 2.5

**Comment by ioquatix** [comment]
This has been implemented.
