### ISSUE TITLE
Async::Notification has trouble when signalling with a plain hash object

### ISSUE THREAD

**Issue by tadman** [socketry/async#67]
The keyword argument causes the hash to be interpreted incorrectly by Ruby:

```ruby
require 'async'
require 'async/notification'

Async do
  notification = Async::Notification.new

  hash = {
    async: true
  }

  notification.signal(hash)
  # => ArgumentError: unknown keyword: :async
end
```

It may be better to go all keyword args, like `signal(value:, task:)` to avoid ambiguity here, though that would be a breaking change.

**Comment by ioquatix** [comment]
This will be fixed in Ruby 3 and is just an unfortunate issue of Ruby  2.x - I'll see if there is anything we can do to fix this, but I've run into this issue before with other libraries. It's one of the motivating factors to remove the implicit conversion of a hash to options.

**Comment by ioquatix** [comment]
Matz has confirmed the decision for Ruby 3.0 however it might be possible to work on 2.x by using empty options, `**{}`.

```
notification.signal(hash, **{})
```

This should be backwards and forwards compatible.
