### ISSUE TITLE
Async::Barrier documentation

### ISSUE THREAD

**Issue by semaperepelitsa** [socketry/async#69]
The documentation string for Barrier is copied exactly from Semaphore. Did that happen by mistake?

https://github.com/socketry/async/blob/17ef44fb0e0bedadcdc96dce60fc4f35d74ac6cc/lib/async/barrier.rb#L25-L27

https://github.com/socketry/async/blob/17ef44fb0e0bedadcdc96dce60fc4f35d74ac6cc/lib/async/semaphore.rb#L23-L25

**Comment by ioquatix** [comment]
Probably.
