### ISSUE TITLE
License of papers/*.pdf

### ISSUE THREAD

**Issue by henrich** [socketry/async#70]
During converting async gem to deb package, I've found that papers/*.pdf license is unclear.
Is it under OSS license?

If not, remove them is fine for me since it's kind of blocker for uploading Debian repository.

**Comment by olleolleolle** [comment]
Perhaps they can be removed from the gemspec files listing? That way, they're in the repo but not passed around in the gem.

**Comment by henrich** [comment]
Thanks, but it's not enough solution since we distribute whole files as orig.tar.{g|x}z files, then I should re-pack upstream changes without those papers for each release. This is because some packages in Debian (and its derivatives) provide their packages like "1.0.0+dfsg-1" (remove non-OSS (= Debian Free Software Guideline) compliant files as its version number says.

It's not convenient for me (I'm so lazy ;) 
So hope to provide an appropriate license file for those PDF files, or just remove them.

**Comment by ioquatix** [comment]
To be honest, it's probably easier for me to remove it, but let me check it first.

**Comment by ioquatix** [comment]
Okay I did some research. Those papers were given to me because they were some of the origins of this kind of task switching system. Well, they are not relevant to the current deisgn but I included them for history. At best, the legal status is ambiguous and so I've removed them. I'll make a release shortly.

**Comment by ioquatix** [comment]
Thanks for bringing this issue to my attention. Fixed in v1.26.2.
