### ISSUE TITLE
Show annotation when logging exception

### ISSUE THREAD

**Issue by emiltin** [socketry/async#78]
Uncaught exceptions in tasks is shown in a format starting with a line like this:
```
  0.0s    error: Async::Task [oid=0x3c] [pid=9016] [2020-12-16 21:01:17 +0100]
```

It would be useful if the task annotation was shown, to quickly identify the failed task.

**Comment by ioquatix** [comment]
It's a nice idea.

**Comment by ioquatix** [comment]
```
require '../lib/async'

Async do |task|
	task.annotate "I'm going to fail!"
	raise "Boom"
end
```

Results in:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/30030/103166266-37dcce80-4885-11eb-8fae-4020b3d909b3.png">

**Comment by ioquatix** [comment]
What do you think?

**Comment by emiltin** [comment]
That would work!

I was wondering if it could be in the line:
Async::Task [oid=0x3c] [pid=9016] [2020-12-16 21:01:17 +0100]

But maybe that's output by Ruby and cannot be changed?

**Comment by ioquatix** [comment]
It's probably more that it's just too long to put on the same line.

**Comment by ioquatix** [comment]
> But maybe that's output by Ruby and cannot be changed?

It's part of the console gem, it can be changed, but I guess we should consider it could be a long annotation.

**Comment by emiltin** [comment]
Right, it can be long. A line of it's own is probably better.

**Comment by ioquatix** [comment]
Just for continuity, I'm still considering how best to integrate this feature: https://bugs.ruby-lang.org/issues/19056

**Comment by ioquatix** [comment]
<img width="1037" alt="Screenshot 2023-06-06 at 11 50 31 AM" src="https://github.com/socketry/async/assets/30030/b7c30691-d23b-4ca6-a4a3-d202de3bba1e">

In the latest commit of Async and Console gems, this is now possible. It's implemented by a shared gem, `finer-annotation`. Anyone can use it.

**Comment by ioquatix** [comment]
If you have any thoughts about better formatting, please feel free to open an issue/PR on the console gem.

https://github.com/socketry/console
