### ISSUE TITLE
Using sync block to guarantee not missing response?

### ISSUE THREAD

**Issue by emiltin** [socketry/async#84]
We're using async in the rsmp gem https://github.com/rsmp-nordic/rsmp which implements the RMSP protocol, used for communicating with traffic lights and other equipment. The gem is used in https://github.com/rsmp-nordic/rsmp_validator for testing the RSMP implementation of equipment.

Tests can be run with equipment emulators running on the same machine, in which case response times can be very short.

The protocol is using plain TCP (not HTTP). Once a connection is established a read loop is started in an async task. This loop will parse and validate incoming messages, and use an Async::Notification to signal to listeners (users of the gem) that a new messages is available.

A common pattern when testing is sending a request and waiting for the response. Since the read loop starts first, it's basically:

```ruby
start_async_read_loop
send_request
wait_for_response
```

Is it possible that we could miss the response if it arrive quickly after we send the request and the read loop gets it before wait_for_response is called?

I suppose this depends on whether writing can yield back to the reactor and on to the read loop?

To guarantee we don't miss the response, I'm currently using an async task to first start listening to the response, and then send the request:

```ruby
Async do |task|
  # read loop
  task.async do
    loop do
      read_and_signal # use Async::Notification to signal 
    end
  end

  # send and wait for response
  collector = task.async do
    wait_for_response # wait for read loop to signal 
  end
  send_request
  collector.wait
end
```

Is my concern about missing responses real? If it is indeed something we need to guard agaist, could I simplify things by using a sync block, something like:

```ruby
start_async_read_loop 
Sync do
  send_request
  wait_for_rseponse
end
```

**Comment by ioquatix** [comment]
It would make more sense to use an `Async::Queue` for reading responses/messages. It is "level triggered". It will contain the message until it is read.

Yes, `Async::Notification` (and `Async::Condition`) are edge triggered. So you will miss notifications if you are not waiting at the time the message is received.

Async does provide some guarantees.

A task will mediately be executed until the first blocking operation. However, you won't always know what this is unless you are careful with your code. It looks like your code should be okay given that we can reason about the order of operations:

``` ruby
Async do |task|
  # read loop
  task.async do
    loop do
      # (1) This is a non-blocking operation and will yield if there are is no response yet:
      read_and_signal # (4) The notification is triggered.
    end
  end

  # send and wait for response
  collector = task.async do
    # (2) We now wait on the signal which is edge triggered:
    wait_for_response # (5) We are signalled and can read the response.
  end

  # (3) We send a request, which causes a response to be sent:
  send_request
  collector.wait
end
```

Therefore, I suggest you don't rely on it.

Can you please tell me more about how your project is being used? Sounds interesting.

**Comment by emiltin** [comment]
OK, sounds like the extra care I'm taking is needed.

Thank you for the suggestion of using an Async::Queue. However there can be several listeners waiting for incoming messages. I'm not sure how that would work with an Async::Queue.

The way it currently works is that there's an Archive, where incoming messages are stored as they arrive. User can add Probes to the archive, passings some filter criteria and the number of messages they need. The probe has an Async::Notification and when the user waits for messages, the probe call wait() on the notification and goes to sleep.

When a message arrives, the archive goes through installed probes and lets them look at the message. If if matches, the probe stores it. When enough has been collected, the probes call signal() on the Async::Notification and the user wakes up and gets the matched messages.

You can see it here if you like: https://github.com/rsmp-nordic/rsmp/blob/master/lib/rsmp/probe.rb

I think this design could be probably be simplified. I will consider you suggestion of using an Async::Queue.


RSMP is maintained by RSMP Nordic, a collaboration between road authorities in the Nordic region. We're working on better tools for automatic testing of RSMP implementations, and have created the rsmp gem as a general library to handle RSMP communication. On top of that we have rsmp_validator which is a suite of rspec tests that uses the rsmp gem to connect to external equipment and then test various parts of the RMSP protocol. Some equipment are quite slow and take a while to establish the connection, so we're keeping a connection open between tests, to avoid very long test running times. To do this we keep an Async::Reactor, and use the rsmp gem inside this reactor to connect to the equipment. In each rspec test we use reactor.run(), run the test, then stop the reactor. See https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/support/test_site.rb#L14

This use of rspec is perhaps a bit unusual, but it works for us. 

As part of the rsmp gem, you can run an RMSP site locally. When you then run the rsmp_validator rspec tests against such a local rsmp site, they run quite quickly. That's when I spotted issues with reponses appearently being missed.

**Comment by emiltin** [comment]
After upgrading to 1.28.2 i had to use reactor.interrupt() instead of reactor.stop() after running each rspec test.

**Comment by emiltin** [comment]
Thanks for the help. Closing
