### ISSUE TITLE
Recurring tasks using Timers inside Async

### ISSUE THREAD

**Issue by bombazook** [socketry/async#88]
Hello. Could you explain the right way to use timers inside Async please?
I'm trying to run several concurrently running recurring tasks and limit concurrence using Async::Semaphore.
I can't use task.sleep to declare recurrence period because it sets new timer on every run (https://github.com/socketry/async/blob/master/lib/async/reactor.rb#L330)
Code below never exit ```task.sleep(10)``` and never release semaphore:
```ruby
Async do |task|
  s = Async::Semaphore.new(5, parent: task)
  timers = Timers::Group.new
  timers.now_and_every(1) do
    if s.blocking?
      Async.logger.debug("blocking")
    else
      s.async do |t|
        Async.logger.debug("acquire")
        task.sleep(10)
        Async.logger.debug("release")
      end
    end
  end
  while true
    timers.fire
  end
end
```
This code works well but I can't use it because of reason I wrote earlier:
```ruby
Async do |task|
  s = Async::Semaphore.new(5, parent: task)
  while true
    if s.blocking?
      Async.logger.debug("blocking")
    else
      s.async do |t|
        Async.logger.debug("acquire")
        task.sleep(10)
        Async.logger.debug("release")
      end
    end
    task.sleep(1) # It shifts a bit because it creates a new timer on every run (https://github.com/socketry/async/blob/master/lib/async/reactor.rb#L330)
  end
end
```
The only way I found to do what I want is to use reactor timers but it looks really ugly:
```ruby
Async do |task|
  s = Async::Semaphore.new(5, parent: task)
  task.reactor.instance_variable_get(:@timers).now_and_every(1) do
    if s.blocking?
      Async.logger.debug("blocking")
    else
      s.async do |t|
        Async.logger.debug("acquire")
        t.sleep(10)
        Async.logger.debug("release")
      end
    end
  end
end
```
Is there a more convenient way to do such things?
Earlier there were several public methods on Reactor for that: https://github.com/socketry/async/commit/d6d80a3d613b359d5fe9c90be63fe64bdb26ba27

Finally, what I'm trying to do is a simple application scheduler (https://gist.github.com/bombazook/5e361dfdc8033af48c19b9723c8346a5)

**Comment by bombazook** [comment]
Well, I found the reason ```sleep``` blocks – I need to yield task in inner infinite loop and return control to reactor:
```ruby
Async do |task|
  s = Async::Semaphore.new(5, parent: task)
  timers = Timers::Group.new
  timers.now_and_every(1) do
    if s.blocking?
      Async.logger.debug("blocking")
    else
      s.async do |t|
        Async.logger.debug("acquire")
        task.sleep(10)
        Async.logger.debug("release")
      end
    end
  end
  while true do
    timers.fire
    task.yield
  end
end
```
But is there a better way to do that?

**Comment by ioquatix** [comment]
Timers in the event loop are not precise, but best effort. It's entirely possible it will be off by a large amount.

A problem which can occur with strict reoccurring timers is that if your event loop is not invoking your timers quickly enough, you might end up with a bottleneck of timers. For example, if your event loop takes 10us per iteration and you set a timer once ever 1us, you may start running into problems.

You would need to implement the policy that suits your situation best, either drop missed iterations, or best effort.

Both options are pretty trivial to implement using `sleep`. In your case, I'd suggest using level triggered conditions, so when the timer is triggered, the condition is triggered, and if possible a task would run. But if you trigger the condition multiple times you won't end up with a backlog.

Personally, I think you'd just be better off creating one `Async::Task` per operation, having a loop with `sleep` and then acquire the semaphore to do your work. If your sleep time is negative, print a warning and iterate again immediately. The timers group provides this in the form of `wait_interval` which can be negative if timers are in the past and should be fired immediately.

```
timers = Timers::Group.new

timers.now_and_every(...) do
  # acquire semaphore and do work ...
end

while interval = timers.wait_interval
 if interval > 0
    task.sleep(interval)
  end

  timers.fire
end
```

**Comment by bombazook** [comment]
Thank you for such a detailed answer. I appreciate your help.
