### ISSUE TITLE
Get the old team back together

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#9]
Hello everyone in no particular order: @halorgium @digitalextremist @e2 @benlangfeld @tarcieri @grantr

I reimplemented here, what I wanted from `celluloid-io`. I bet everyone has moved on in one way or another, but I just wanted to stay thanks for everyone's effort on `celluloid`, and going forward I think there is an opportunity to take the best ideas from `celluloid`, and perhaps build on them here.

A few things on the agenda to figure out:

- I'm going to be honest, based on where things have ended up for `celluloid`, I don't know if it's possible to recover. I think we need to consider what strategy we adopt going forward for that org/gem - do we mark it as deprecated?
- Tabs/Spaces. I'm firmly in the tabs camp for my own code, but I'm happy to consider compromise if it's a deal breaker for other developers who would be actively willing to contribute.
- Directions going forward. I'm planning to retain full control of this project for the foreseeable future. I'm going to be a dictator to start with. The core `async` gem is almost feature complete IMHO, and doesn't require a lot of work, but it DOES require documentation, testing, and momentum. I'd like to keep the `async-*` namespace really tight to start with, but I do think we need some additional bits to make usage easier.

Projects on the table that I can think of:

- `async-http` - light-weight HTTP client and server.
- `async-wrap` - light-weight wrappers to support systems that allow `socket_class:` option.
- `async-dns` - working and almost done.
- `async-actor` - light-weight actor implementation with message passing, ala celluloid.

**Comment by benlangfeld** [comment]
I've somewhat moved on from these sort of projects in Ruby, but I wish you the best of luck!

**Comment by ioquatix** [comment]
It also seems like we might have some new team members: @picatz and @huba

**Comment by ioquatix** [comment]
Also, just to add, while I feel the current code base is fairly solid, there is every chance a major issue may show up with the design and I am not going to hesitate to rip out and reengineer whatever needs to be done to ensure it has the correct design/semantic model.

**Comment by ioquatix** [comment]
Sorry, this wasn't supposed to be closed, typed the wrong number :D

**Comment by ioquatix** [comment]
I will provide a brief update here just in case any of the original authors are interested.

- I've now implemented a HTTP server [falcon] which builds on [async-http] and [async-io]. It performs well in typical usage scenarios.
- I've extracted general RSpec integrations into [async-rspec].
- I've improved [async-dns].
- I've added [async-container] for forked/threaded server handling.

At this point, I'm going to close this issue. If you are interested in helping with any of the above projects, please get involved. I hope to release a full set of 1.0 releases before the end of the year.
