### ISSUE TITLE
Memory leak in Async::Scheduler (lots of File instances with same file descriptor)

### ISSUE THREAD

**Issue by casperisfine** [socketry/async#90]
Apologies for not providing a reproduction script, but I'm having trouble reproducing the issue in isolation.

For context the app where it happens is a Slack bot, so it listen to a websocket.

### Observations

After upgrading to ruby 3.0.0 we observed a major memory leak (we're talking about GiB of RAM used in mere minutes).

Using `ObjectSpace.dump_all`, i was able to pinpoint the leak to `Async::Scheduler`, after handling just a command or two, the heap contains over 150k instance of `File`, all with the same file descriptor, and they are held by the scheduler: https://github.com/socketry/async/blob/2b5d37a9e1eb2d2b1f0d500e5df406d6876c96e6/lib/async/scheduler.rb#L54

I've put some debug code, and found the instances are instantiated by `Scheduler#io_wait`:

```
{"address":"0x7ff0295aacc8", "type":"FILE", "class":"0x7ff02489c418", "fd":25, "references":["0x7ff0295aacc8"], "memsize":240}
/Users/byroot/.gem/ruby/3.0.0/gems/async-1.28.3/lib/async/scheduler.rb:63:in `io_wait'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/select_thread.rb:142:in `send'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/select_thread.rb:142:in `add_to_select'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/packet_sender.rb:529:in `send_dnsruby'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/packet_sender.rb:374:in `send_async'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:1019:in `block (3 levels) in tick'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:1005:in `each'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:1005:in `block (2 levels) in tick'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:995:in `each'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:995:in `block in tick'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:993:in `synchronize'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:993:in `tick'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:928:in `send_async'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:402:in `send_async'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:252:in `send_message'
/Users/byroot/.gem/ruby/3.0.0/gems/dnsruby-1.61.5/lib/dnsruby/resolver.rb:204:in `query'
```

This happens repeatedly, almost like it is stuck in an infinite loop, and on every call the `File` instance is different but points to the same `fd`:

```
{"address":"0x7ff0295b3378", "type":"FILE", "class":"0x7ff02489c418", "fd":25, "references":["0x7ff0295b3378"], "memsize":240}
{"address":"0x7ff0294edfb0", "type":"FILE", "class":"0x7ff02489c418", "fd":25, "references":["0x7ff0294edfb0"], "memsize":240}
{"address":"0x7ff0295077d0", "type":"FILE", "class":"0x7ff02489c418", "fd":25, "references":["0x7ff0295077d0"], "memsize":240}
....
```

At this stage I'm not sure wether it's a bug in Ruby 3.0 fiber scheduler, or a bug in the async gem, or in dnsruby. I'll try some more to extract a reproduction script, but I figured this description might ring a bell to you.

cc @MichaelM-Shopify

**Comment by ioquatix** [comment]
It's a bug... we should be caching this.

**Comment by casperisfine** [comment]
Any idea where the bug is? I mean is it in `async` or in Ruby itself?

**Comment by casperisfine** [comment]
ALso I'm wondering if it wouldn't make more sense for `@wrappers` to be a `WeakMap`.

**Comment by ioquatix** [comment]
`io` as a key is not working correctly.

**Comment by ioquatix** [comment]
https://github.com/socketry/async/pull/97 as suggested.

**Comment by ioquatix** [comment]
Okay, after considering the options, I decided to remove the cache. It's going to be less useful going forward anyway as we look to support one-shot operations with `io_uring`, etc.

**Comment by ioquatix** [comment]
Can you please check if this is still a problem?

**Comment by casperisfine** [comment]
I just tested 1.28.6, and can confirm the memory leak no longer triggers. Thanks!

**Comment by ioquatix** [comment]
Thanks!
