### ISSUE TITLE
StandardError is getting printed to log

### ISSUE THREAD

**Issue by igor-makarov** [socketry/async#91]
First time here. Me and @jasl are working on adopting `async-http` in CocoaPods. 

I've noticed the [following line](https://github.com/socketry/async/blob/2b5d37a9e1eb2d2b1f0d500e5df406d6876c96e6/lib/async/task.rb#L271):
```ruby
rescue StandardError => error
	fail!(error, false)
```

I've realized that this has been causing some odd behavior, namely [log noise](https://github.com/CocoaPods/Core/pull/669/checks?check_run_id=1720116568#step:7:1417) where none should be expected. The relevant test awaits on the task and rescues the exception (because it's expected).
 
Is there a reason why `StandardError` fail with `propagate=false`? If so, why is the error propagated anyway?

Thank you!

**Comment by jasl** [comment]
For the context, the WIP PR is https://github.com/CocoaPods/Core/pull/669

The core part of async download file implementation is https://github.com/CocoaPods/Core/blob/3b63a46a5fd185c5eb8f99f02276088991b06178/lib/cocoapods-core/cdn_source.rb#L373-L509

**Comment by igor-makarov** [comment]
I've added a test in a draft PR: 
https://github.com/socketry/async/pull/92/files
Here's the aforementioned log noise:
https://github.com/socketry/async/pull/92/checks#step:4:315

**Comment by ioquatix** [comment]
One of the biggest problems I had with celluloid (and some other concurrency frameworks) was that errors could be swallowed by the concurrency "task". IF this happened, your system could be collapsing and you'd never know about it.

When I designed async, I made an explicit choice that errors should be reported by default.

If you have a task like this:

```
Async do
	something_that_might_fail
end
```

You will get an error printed out to `stderr` if it fails. There is a special case, if you wait on the task, before it throws the error, it will not be printed, because you have indicated that you will handle it. However, this case is racy...

If the failure is expected, you need to write this:

```
Async do
	something_that_might_fail
rescue StandardError => error
	# result of task is the error
	error
end

# Will never log error.

task.wait # Waits for potential result or error.
```

In this way, you are explicitly handling the error.

At one point as an experiment we did allow something like this:

```
task = Async(propagate: true) do
	something_that_might_fail
end

# Will never log error.

task.wait # Waits for potential result or error.
```

This form will not print out the error in any case, and you are opting in to call `wait`. However, I didn't feel there was a sufficiently strong case for this so opted not to introduce it at that time.

**Comment by jasl** [comment]
> Async do
> 	something_that_might_fail
> rescue StandardError => error
> 	# result of task is the error
> 	error
> end

I remember I was did like this

```ruby
Async do
	something_that_might_fail
rescue StandardError => error
	# result of task is the error
	error
end
```

but no effect, maybe I was doing wrong, I'll retry later

**Comment by ioquatix** [comment]
You are probably calling `task.wait` which is raising the error, e.g.

```
Async do
  items.each{Async{...}}
    .map(&:wait) # will throw exception here
end # will log exception because it died.
```

**Comment by igor-makarov** [comment]
@ioquatix I've made a PR #92  that exemplifies the problem - here's the relevant snippet:
```
Sync do
	Async::Task.current.with_timeout(10) do 
		raise StandardError, "brain not provided"
	end
end
```

Log noise can be found here: https://github.com/socketry/async/pull/92/checks#step:4:315

Can this be done some other way?

**Comment by igor-makarov** [comment]
@ioquatix The main problem is that the errors gets logged before it's caught, somehow because it's a `StandardError`.

**Comment by ioquatix** [comment]
> the wait happens after the exception occurs?

That's exactly what's happening.

For `Sync` we could implement the propagate option.

**Comment by igor-makarov** [comment]
@ioquatix same happens with `Async`:

```
Async do |task|
	expect do 
		task.async do
			raise StandardError, "brain not provided"
		end.wait
	end.to raise_exception(StandardError, /brain/)
end
```

**Comment by ioquatix** [comment]
`Sync` and `Async` are semantically identical at the top level. It only differs when they are nested.

**Comment by ioquatix** [comment]
Here is one potential solution:

https://github.com/socketry/async/pull/94

**Comment by jasl** [comment]
In CocoaPods case, in my opinion, the requirement is, some errors (such as Timeout, SocketError, etc.) which could raising in task is expected, 
we don't want to log it or it may made user confusing (because they're expected),
we just want to pop these errors to main context and handle them

**Comment by ioquatix** [comment]
If you use `Sync` the error will never be logged. If you use `async` several options are presented to catch those errors before they are logged.
