### ISSUE TITLE
calling system()

### ISSUE THREAD

**Issue by emiltin** [socketry/async#93]
Can calling out to system() interfere with the async concurrency?

We're seeing a case where an rspec test fails, with the backtrace pointing to code in the previous test. And that previous test uses system() to run a script.

**Comment by ioquatix** [comment]
No it shouldn't interfere with async concurrency, but it is a system call we want to make asynchronous in Ruby 3.1.

Can you give me more details?

**Comment by emiltin** [comment]
OK.
We're using RSpec and Async to test the RSMP protocol implementation of a traffic light software simulator. The scripts is used to simulate mouse click in the simulator GUI, as a workaround for activating alarms that would otherwise require a physical lamp or piece of equipment. I don't have details on how the script works, but @otterdahl can provide details if needed.
I'm not sure what's going on, which is why i asked if system() is expected to be safe form an async point of view.

**Comment by emiltin** [comment]
We're tracking the issue in https://github.com/rsmp-nordic/rsmp_validator/issues/47
